package server

import (
	"crypto/tls"
	"fmt"
	"html/template"
	"net/http"
	"os"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/rs/zerolog"

	db "Intelligent_Dev_ToolKit_Odoo/db/sqlc"
	// docs is generated by Swag CLI.
	_ "Intelligent_Dev_ToolKit_Odoo/docs"
	"Intelligent_Dev_ToolKit_Odoo/internal/cache"
	"Intelligent_Dev_ToolKit_Odoo/internal/config"
	"Intelligent_Dev_ToolKit_Odoo/internal/handler"
	"Intelligent_Dev_ToolKit_Odoo/internal/service"
	"Intelligent_Dev_ToolKit_Odoo/internal/storage"
	"Intelligent_Dev_ToolKit_Odoo/internal/token"
)

type Server struct {
	store      db.Store
	cache      *cache.RedisClient // optional in-memory cache (Redis)
	config     *config.Config
	router     *chi.Mux
	logger     *zerolog.Logger
	handler    *handler.Handlers
	services   *service.Services
	tokenMaker token.Maker
	// Safe HTML template rendering
	template *template.Template
}

func NewServer(store db.Store, redisCache *cache.RedisClient, cfg config.Config) (*Server, error) {

	tokenMaker, err := token.NewJWTMaker(cfg.TokenSymmetricKey)
	if err != nil {
		return nil, fmt.Errorf("cannot create token maker: %w", err)
	}

	server := &Server{
		store:      store,
		cache:      redisCache,
		config:     &cfg,
		tokenMaker: tokenMaker,
		template:   template.New(""),
	}

	// Create logger
	logger := zerolog.New(os.Stderr).With().Timestamp().Logger()
	if server.config.Environment == config.EnvironmentDevelopment {
		logger = zerolog.New(zerolog.ConsoleWriter{Out: os.Stderr}).With().Timestamp().Logger()
	}
	server.logger = &logger

	// Instantiate services container
	serviceConfig := service.DefaultConfig()
	// Customize service config from main config
	serviceConfig.Auth.AccessTokenDuration = cfg.AccessTokenDuration
	serviceConfig.Auth.RefreshTokenDuration = cfg.RefreshTokenDuration
	services := service.NewServices(server.store, server.cache, server.tokenMaker, &service.Config{
		Auth: service.AuthConfig{
			AccessTokenDuration:  cfg.AccessTokenDuration,
			RefreshTokenDuration: cfg.RefreshTokenDuration,
			PasswordMinLength:    8,
			BcryptCost:           10,
			Environment:          cfg.Environment,
			// Real SMTP (Resend, SendGrid, etc.) — used in staging/production
			SMTPHost:     cfg.SMTPHost,
			SMTPPort:     cfg.SMTPPort,
			SMTPUsername: cfg.SMTPUsername,
			SMTPPassword: cfg.SMTPPassword,
			SMTPFrom:     cfg.EmailFrom,
			// MailHog — used automatically in development
			MailhogHost: "localhost",
			MailhogPort: 1025,
			AppBaseURL:  cfg.ClientAppURL,
		},
	})
	server.services = services

	// Build optional handler dependencies.
	deps := &handler.HandlerDeps{}

	if redisCache != nil {
		deps.RedisClient = redisCache.Client
		deps.RedisCache = redisCache
		deps.IngestStreamName = cfg.RedisStreamIngest
	}

	if cfg.S3Bucket != "" && cfg.S3AccessKey != "" {
		s3Client, s3Err := storage.NewS3Client(storage.S3Config{
			Endpoint:       cfg.S3Endpoint,
			Bucket:         cfg.S3Bucket,
			Region:         cfg.S3Region,
			AccessKey:      cfg.S3AccessKey,
			SecretKey:      cfg.S3SecretKey,
			ForcePathStyle: cfg.S3ForcePathStyle,
		})
		if s3Err != nil {
			server.logger.Warn().Err(s3Err).Msg("S3 init failed — agent distribution endpoints disabled")
		} else {
			deps.S3Client = s3Client
		}
	}

	handlers := handler.NewHandlers(services, server.store, server.logger, deps)
	server.handler = handlers

	server.setupRoutes()
	return server, nil
}

func (s *Server) Start(address string) error {
	// Good practice: enforce timeouts for servers you create!
	srv := &http.Server{
		Addr:         address,
		Handler:      s.router,
		ReadTimeout:  5 * time.Second,
		WriteTimeout: 10 * time.Second,
		IdleTimeout:  120 * time.Second,
		TLSConfig: &tls.Config{
			//gosec:G402
			// Force clients to use secure TLS versions
			MinVersion: tls.VersionTLS12,
			// Best practice: enforce server-side cipher suite preferences
			PreferServerCipherSuites: true,
			CurvePreferences: []tls.CurveID{
				tls.X25519,
				tls.CurveP256,
			},
			CipherSuites: []uint16{
				tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
				tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
				tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
				tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
				tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
				tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
			},
		},
	}
	// Use ListenAndServeTLS instead of ListenAndServe
	s.router.Use(func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			w.Header().Add("Strict-Transport-Security", "max-age=63072000; includeSubDomains")
			next.ServeHTTP(w, r)
		})
	})
	return srv.ListenAndServeTLS("cert.pem", "key.pem")
}

func (s *Server) Router() http.Handler {
	return s.router
}
