// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: alerts.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const acknowledgeAlert = `-- name: AcknowledgeAlert :one
UPDATE alerts
SET
    acknowledged = true,
    acknowledged_by = $2,
    acknowledged_at = now()
WHERE id = $1 AND env_id = $3
RETURNING id, env_id, type, severity, message, metadata, acknowledged, acknowledged_by, acknowledged_at, created_at
`

type AcknowledgeAlertParams struct {
	ID             uuid.UUID  `db:"id" json:"id"`
	AcknowledgedBy *uuid.UUID `db:"acknowledged_by" json:"acknowledged_by"`
	EnvID          uuid.UUID  `db:"env_id" json:"env_id"`
}

func (q *Queries) AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, acknowledgeAlert, arg.ID, arg.AcknowledgedBy, arg.EnvID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Type,
		&i.Severity,
		&i.Message,
		&i.Metadata,
		&i.Acknowledged,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.CreatedAt,
	)
	return i, err
}

const acknowledgeAllAlerts = `-- name: AcknowledgeAllAlerts :execresult
UPDATE alerts
SET
    acknowledged = true,
    acknowledged_by = $2,
    acknowledged_at = now()
WHERE env_id = $1 AND acknowledged = false
`

type AcknowledgeAllAlertsParams struct {
	EnvID          uuid.UUID  `db:"env_id" json:"env_id"`
	AcknowledgedBy *uuid.UUID `db:"acknowledged_by" json:"acknowledged_by"`
}

func (q *Queries) AcknowledgeAllAlerts(ctx context.Context, arg AcknowledgeAllAlertsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, acknowledgeAllAlerts, arg.EnvID, arg.AcknowledgedBy)
}

const countUnacknowledgedAlerts = `-- name: CountUnacknowledgedAlerts :one
SELECT count(*) FROM alerts
WHERE env_id = $1 AND acknowledged = false
`

func (q *Queries) CountUnacknowledgedAlerts(ctx context.Context, envID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnacknowledgedAlerts, envID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAlert = `-- name: CreateAlert :one

INSERT INTO alerts (
    env_id,
    type,
    severity,
    message,
    metadata
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, env_id, type, severity, message, metadata, acknowledged, acknowledged_by, acknowledged_at, created_at
`

type CreateAlertParams struct {
	EnvID    uuid.UUID       `db:"env_id" json:"env_id"`
	Type     string          `db:"type" json:"type"`
	Severity string          `db:"severity" json:"severity"`
	Message  string          `db:"message" json:"message"`
	Metadata json.RawMessage `db:"metadata" json:"metadata"`
}

// ════════════════════════════════════════════
//
//	Alerts
//
// ════════════════════════════════════════════
func (q *Queries) CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error) {
	row := q.db.QueryRow(ctx, createAlert,
		arg.EnvID,
		arg.Type,
		arg.Severity,
		arg.Message,
		arg.Metadata,
	)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Type,
		&i.Severity,
		&i.Message,
		&i.Metadata,
		&i.Acknowledged,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createAlertDelivery = `-- name: CreateAlertDelivery :one

INSERT INTO alert_deliveries (
    alert_id,
    channel_id
) VALUES (
    $1, $2
) RETURNING id, alert_id, channel_id, status, attempt, error, sent_at, created_at
`

type CreateAlertDeliveryParams struct {
	AlertID   uuid.UUID `db:"alert_id" json:"alert_id"`
	ChannelID uuid.UUID `db:"channel_id" json:"channel_id"`
}

// ════════════════════════════════════════════
//
//	Alert Deliveries (used by notification worker)
//
// ════════════════════════════════════════════
func (q *Queries) CreateAlertDelivery(ctx context.Context, arg CreateAlertDeliveryParams) (AlertDelivery, error) {
	row := q.db.QueryRow(ctx, createAlertDelivery, arg.AlertID, arg.ChannelID)
	var i AlertDelivery
	err := row.Scan(
		&i.ID,
		&i.AlertID,
		&i.ChannelID,
		&i.Status,
		&i.Attempt,
		&i.Error,
		&i.SentAt,
		&i.CreatedAt,
	)
	return i, err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one

INSERT INTO notification_channels (
    tenant_id,
    name,
    type,
    config,
    is_active
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, tenant_id, name, type, config, is_active, created_at
`

type CreateNotificationChannelParams struct {
	TenantID uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	Name     string          `db:"name" json:"name"`
	Type     string          `db:"type" json:"type"`
	Config   json.RawMessage `db:"config" json:"config"`
	IsActive bool            `db:"is_active" json:"is_active"`
}

// ════════════════════════════════════════════
//
//	Notification Channels
//
// ════════════════════════════════════════════
func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.TenantID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.IsActive,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteNotificationChannel = `-- name: DeleteNotificationChannel :exec
DELETE FROM notification_channels
WHERE id = $1 AND tenant_id = $2
`

type DeleteNotificationChannelParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteNotificationChannel(ctx context.Context, arg DeleteNotificationChannelParams) error {
	_, err := q.db.Exec(ctx, deleteNotificationChannel, arg.ID, arg.TenantID)
	return err
}

const deleteOldAlerts = `-- name: DeleteOldAlerts :execresult
DELETE FROM alerts
WHERE env_id IN (
    SELECT id FROM environments WHERE tenant_id = $1
)
AND alerts.created_at < $2
`

type DeleteOldAlertsParams struct {
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) DeleteOldAlerts(ctx context.Context, arg DeleteOldAlertsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldAlerts, arg.TenantID, arg.CreatedAt)
}

const getAlert = `-- name: GetAlert :one
SELECT id, env_id, type, severity, message, metadata, acknowledged, acknowledged_by, acknowledged_at, created_at FROM alerts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAlert(ctx context.Context, id uuid.UUID) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlert, id)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Type,
		&i.Severity,
		&i.Message,
		&i.Metadata,
		&i.Acknowledged,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAlertByID = `-- name: GetAlertByID :one
SELECT id, env_id, type, severity, message, metadata, acknowledged, acknowledged_by, acknowledged_at, created_at FROM alerts
WHERE id = $1 AND env_id = $2
LIMIT 1
`

type GetAlertByIDParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
}

func (q *Queries) GetAlertByID(ctx context.Context, arg GetAlertByIDParams) (Alert, error) {
	row := q.db.QueryRow(ctx, getAlertByID, arg.ID, arg.EnvID)
	var i Alert
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Type,
		&i.Severity,
		&i.Message,
		&i.Metadata,
		&i.Acknowledged,
		&i.AcknowledgedBy,
		&i.AcknowledgedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, tenant_id, name, type, config, is_active, created_at FROM notification_channels
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetNotificationChannelParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, arg.ID, arg.TenantID)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const hasRecentAlert = `-- name: HasRecentAlert :one
SELECT EXISTS (
    SELECT 1 FROM alerts
    WHERE env_id = $1
      AND type = $2
      AND metadata @> $3::jsonb
      AND created_at > now() - make_interval(mins => $4::int)
) AS exists
`

type HasRecentAlertParams struct {
	EnvID   uuid.UUID       `db:"env_id" json:"env_id"`
	Type    string          `db:"type" json:"type"`
	Column3 json.RawMessage `db:"column_3" json:"column_3"`
	Column4 int32           `db:"column_4" json:"column_4"`
}

func (q *Queries) HasRecentAlert(ctx context.Context, arg HasRecentAlertParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRecentAlert,
		arg.EnvID,
		arg.Type,
		arg.Column3,
		arg.Column4,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listActiveNotificationChannels = `-- name: ListActiveNotificationChannels :many
SELECT id, tenant_id, name, type, config, is_active, created_at FROM notification_channels nc
WHERE nc.tenant_id = $1 AND nc.is_active = true
ORDER BY nc.created_at
`

func (q *Queries) ListActiveNotificationChannels(ctx context.Context, tenantID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listActiveNotificationChannels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertDeliveries = `-- name: ListAlertDeliveries :many
SELECT id, alert_id, channel_id, status, attempt, error, sent_at, created_at FROM alert_deliveries
WHERE alert_id = $1
ORDER BY alert_deliveries.created_at ASC
`

func (q *Queries) ListAlertDeliveries(ctx context.Context, alertID uuid.UUID) ([]AlertDelivery, error) {
	rows, err := q.db.Query(ctx, listAlertDeliveries, alertID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AlertDelivery{}
	for rows.Next() {
		var i AlertDelivery
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.ChannelID,
			&i.Status,
			&i.Attempt,
			&i.Error,
			&i.SentAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlerts = `-- name: ListAlerts :many
SELECT id, env_id, type, severity, message, metadata, acknowledged, acknowledged_by, acknowledged_at, created_at FROM alerts a
WHERE a.env_id = $1
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAlertsParams struct {
	EnvID  uuid.UUID `db:"env_id" json:"env_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListAlerts(ctx context.Context, arg ListAlertsParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlerts, arg.EnvID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Type,
			&i.Severity,
			&i.Message,
			&i.Metadata,
			&i.Acknowledged,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAlertsByType = `-- name: ListAlertsByType :many
SELECT id, env_id, type, severity, message, metadata, acknowledged, acknowledged_by, acknowledged_at, created_at FROM alerts a
WHERE a.env_id = $1 AND a.type = $2
ORDER BY a.created_at DESC
LIMIT $3
`

type ListAlertsByTypeParams struct {
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
	Type  string    `db:"type" json:"type"`
	Limit int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListAlertsByType(ctx context.Context, arg ListAlertsByTypeParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsByType, arg.EnvID, arg.Type, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Type,
			&i.Severity,
			&i.Message,
			&i.Metadata,
			&i.Acknowledged,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, tenant_id, name, type, config, is_active, created_at FROM notification_channels nc
WHERE nc.tenant_id = $1
ORDER BY nc.created_at
`

func (q *Queries) ListNotificationChannels(ctx context.Context, tenantID uuid.UUID) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationChannel{}
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Type,
			&i.Config,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingDeliveries = `-- name: ListPendingDeliveries :many
SELECT
    ad.id,
    ad.alert_id,
    ad.channel_id,
    ad.status,
    ad.attempt,
    ad.error,
    ad.sent_at,
    ad.created_at,
    nc.type AS channel_type,
    nc.config AS channel_config,
    a.type AS alert_type,
    a.severity AS alert_severity,
    a.message AS alert_message,
    a.metadata AS alert_metadata
FROM alert_deliveries ad
JOIN notification_channels nc ON ad.channel_id = nc.id
JOIN alerts a ON ad.alert_id = a.id
WHERE ad.status = 'pending'
ORDER BY ad.created_at ASC
LIMIT $1
`

type ListPendingDeliveriesRow struct {
	ID            uuid.UUID       `db:"id" json:"id"`
	AlertID       uuid.UUID       `db:"alert_id" json:"alert_id"`
	ChannelID     uuid.UUID       `db:"channel_id" json:"channel_id"`
	Status        string          `db:"status" json:"status"`
	Attempt       int32           `db:"attempt" json:"attempt"`
	Error         *string         `db:"error" json:"error"`
	SentAt        *time.Time      `db:"sent_at" json:"sent_at"`
	CreatedAt     time.Time       `db:"created_at" json:"created_at"`
	ChannelType   string          `db:"channel_type" json:"channel_type"`
	ChannelConfig json.RawMessage `db:"channel_config" json:"channel_config"`
	AlertType     string          `db:"alert_type" json:"alert_type"`
	AlertSeverity string          `db:"alert_severity" json:"alert_severity"`
	AlertMessage  string          `db:"alert_message" json:"alert_message"`
	AlertMetadata json.RawMessage `db:"alert_metadata" json:"alert_metadata"`
}

func (q *Queries) ListPendingDeliveries(ctx context.Context, limit int32) ([]ListPendingDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listPendingDeliveries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingDeliveriesRow{}
	for rows.Next() {
		var i ListPendingDeliveriesRow
		if err := rows.Scan(
			&i.ID,
			&i.AlertID,
			&i.ChannelID,
			&i.Status,
			&i.Attempt,
			&i.Error,
			&i.SentAt,
			&i.CreatedAt,
			&i.ChannelType,
			&i.ChannelConfig,
			&i.AlertType,
			&i.AlertSeverity,
			&i.AlertMessage,
			&i.AlertMetadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnacknowledgedAlerts = `-- name: ListUnacknowledgedAlerts :many
SELECT id, env_id, type, severity, message, metadata, acknowledged, acknowledged_by, acknowledged_at, created_at FROM alerts a
WHERE a.env_id = $1 AND a.acknowledged = false
ORDER BY a.created_at DESC
LIMIT $2
`

type ListUnacknowledgedAlertsParams struct {
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
	Limit int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListUnacknowledgedAlerts(ctx context.Context, arg ListUnacknowledgedAlertsParams) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listUnacknowledgedAlerts, arg.EnvID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Alert{}
	for rows.Next() {
		var i Alert
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Type,
			&i.Severity,
			&i.Message,
			&i.Metadata,
			&i.Acknowledged,
			&i.AcknowledgedBy,
			&i.AcknowledgedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeliveryFailed = `-- name: MarkDeliveryFailed :exec
UPDATE alert_deliveries
SET
    status = 'failed',
    error = $2,
    attempt = attempt + 1
WHERE id = $1
`

type MarkDeliveryFailedParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Error *string   `db:"error" json:"error"`
}

func (q *Queries) MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error {
	_, err := q.db.Exec(ctx, markDeliveryFailed, arg.ID, arg.Error)
	return err
}

const markDeliverySent = `-- name: MarkDeliverySent :exec
UPDATE alert_deliveries
SET
    status = 'sent',
    sent_at = now()
WHERE id = $1
`

func (q *Queries) MarkDeliverySent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markDeliverySent, id)
	return err
}

const retryFailedDeliveries = `-- name: RetryFailedDeliveries :execresult
UPDATE alert_deliveries
SET status = 'pending'
WHERE status = 'failed'
  AND attempt < $1
  AND alert_deliveries.created_at > now() - interval '24 hours'
`

func (q *Queries) RetryFailedDeliveries(ctx context.Context, attempt int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, retryFailedDeliveries, attempt)
}

const updateNotificationChannel = `-- name: UpdateNotificationChannel :one
UPDATE notification_channels
SET
    name = $2,
    type = $3,
    config = $4,
    is_active = $5
WHERE id = $1 AND tenant_id = $6
RETURNING id, tenant_id, name, type, config, is_active, created_at
`

type UpdateNotificationChannelParams struct {
	ID       uuid.UUID       `db:"id" json:"id"`
	Name     string          `db:"name" json:"name"`
	Type     string          `db:"type" json:"type"`
	Config   json.RawMessage `db:"config" json:"config"`
	IsActive bool            `db:"is_active" json:"is_active"`
	TenantID uuid.UUID       `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannel,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Config,
		arg.IsActive,
		arg.TenantID,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Type,
		&i.Config,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
