// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: anonymization.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createAnonProfile = `-- name: CreateAnonProfile :one
INSERT INTO anon_profiles (
    tenant_id,
    created_by,
    name,
    source_env,
    target_env,
    field_rules,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, tenant_id, created_by, name, source_env, target_env, field_rules, status, last_run, last_run_by, audit_ref, created_at, updated_at
`

type CreateAnonProfileParams struct {
	TenantID   uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	CreatedBy  *uuid.UUID      `db:"created_by" json:"created_by"`
	Name       string          `db:"name" json:"name"`
	SourceEnv  *uuid.UUID      `db:"source_env" json:"source_env"`
	TargetEnv  *uuid.UUID      `db:"target_env" json:"target_env"`
	FieldRules json.RawMessage `db:"field_rules" json:"field_rules"`
	Status     string          `db:"status" json:"status"`
}

func (q *Queries) CreateAnonProfile(ctx context.Context, arg CreateAnonProfileParams) (AnonProfile, error) {
	row := q.db.QueryRow(ctx, createAnonProfile,
		arg.TenantID,
		arg.CreatedBy,
		arg.Name,
		arg.SourceEnv,
		arg.TargetEnv,
		arg.FieldRules,
		arg.Status,
	)
	var i AnonProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Name,
		&i.SourceEnv,
		&i.TargetEnv,
		&i.FieldRules,
		&i.Status,
		&i.LastRun,
		&i.LastRunBy,
		&i.AuditRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAnonProfile = `-- name: DeleteAnonProfile :exec
DELETE FROM anon_profiles
WHERE id = $1 AND tenant_id = $2
`

type DeleteAnonProfileParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteAnonProfile(ctx context.Context, arg DeleteAnonProfileParams) error {
	_, err := q.db.Exec(ctx, deleteAnonProfile, arg.ID, arg.TenantID)
	return err
}

const getAnonProfile = `-- name: GetAnonProfile :one
SELECT id, tenant_id, created_by, name, source_env, target_env, field_rules, status, last_run, last_run_by, audit_ref, created_at, updated_at FROM anon_profiles
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetAnonProfileParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetAnonProfile(ctx context.Context, arg GetAnonProfileParams) (AnonProfile, error) {
	row := q.db.QueryRow(ctx, getAnonProfile, arg.ID, arg.TenantID)
	var i AnonProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Name,
		&i.SourceEnv,
		&i.TargetEnv,
		&i.FieldRules,
		&i.Status,
		&i.LastRun,
		&i.LastRunBy,
		&i.AuditRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAnonProfileByID = `-- name: GetAnonProfileByID :one
SELECT id, tenant_id, created_by, name, source_env, target_env, field_rules, status, last_run, last_run_by, audit_ref, created_at, updated_at FROM anon_profiles
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAnonProfileByID(ctx context.Context, id uuid.UUID) (AnonProfile, error) {
	row := q.db.QueryRow(ctx, getAnonProfileByID, id)
	var i AnonProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Name,
		&i.SourceEnv,
		&i.TargetEnv,
		&i.FieldRules,
		&i.Status,
		&i.LastRun,
		&i.LastRunBy,
		&i.AuditRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAnonProfiles = `-- name: ListAnonProfiles :many
SELECT id, tenant_id, created_by, name, source_env, target_env, field_rules, status, last_run, last_run_by, audit_ref, created_at, updated_at FROM anon_profiles
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAnonProfiles(ctx context.Context, tenantID uuid.UUID) ([]AnonProfile, error) {
	rows, err := q.db.Query(ctx, listAnonProfiles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AnonProfile{}
	for rows.Next() {
		var i AnonProfile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CreatedBy,
			&i.Name,
			&i.SourceEnv,
			&i.TargetEnv,
			&i.FieldRules,
			&i.Status,
			&i.LastRun,
			&i.LastRunBy,
			&i.AuditRef,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAnonProfile = `-- name: UpdateAnonProfile :one
UPDATE anon_profiles
SET
    name = $2,
    source_env = $3,
    target_env = $4,
    field_rules = $5,
    updated_at = now()
WHERE id = $1 AND tenant_id = $6
RETURNING id, tenant_id, created_by, name, source_env, target_env, field_rules, status, last_run, last_run_by, audit_ref, created_at, updated_at
`

type UpdateAnonProfileParams struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	Name       string          `db:"name" json:"name"`
	SourceEnv  *uuid.UUID      `db:"source_env" json:"source_env"`
	TargetEnv  *uuid.UUID      `db:"target_env" json:"target_env"`
	FieldRules json.RawMessage `db:"field_rules" json:"field_rules"`
	TenantID   uuid.UUID       `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) UpdateAnonProfile(ctx context.Context, arg UpdateAnonProfileParams) (AnonProfile, error) {
	row := q.db.QueryRow(ctx, updateAnonProfile,
		arg.ID,
		arg.Name,
		arg.SourceEnv,
		arg.TargetEnv,
		arg.FieldRules,
		arg.TenantID,
	)
	var i AnonProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Name,
		&i.SourceEnv,
		&i.TargetEnv,
		&i.FieldRules,
		&i.Status,
		&i.LastRun,
		&i.LastRunBy,
		&i.AuditRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAnonProfileStatus = `-- name: UpdateAnonProfileStatus :one
UPDATE anon_profiles
SET
    status = $2,
    last_run = CASE WHEN $2 = 'completed' THEN now() ELSE last_run END,
    last_run_by = $3,
    audit_ref = $4,
    updated_at = now()
WHERE id = $1 AND tenant_id = $5
RETURNING id, tenant_id, created_by, name, source_env, target_env, field_rules, status, last_run, last_run_by, audit_ref, created_at, updated_at
`

type UpdateAnonProfileStatusParams struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	Status    string     `db:"status" json:"status"`
	LastRunBy *uuid.UUID `db:"last_run_by" json:"last_run_by"`
	AuditRef  *string    `db:"audit_ref" json:"audit_ref"`
	TenantID  uuid.UUID  `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) UpdateAnonProfileStatus(ctx context.Context, arg UpdateAnonProfileStatusParams) (AnonProfile, error) {
	row := q.db.QueryRow(ctx, updateAnonProfileStatus,
		arg.ID,
		arg.Status,
		arg.LastRunBy,
		arg.AuditRef,
		arg.TenantID,
	)
	var i AnonProfile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Name,
		&i.SourceEnv,
		&i.TargetEnv,
		&i.FieldRules,
		&i.Status,
		&i.LastRun,
		&i.LastRunBy,
		&i.AuditRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
