// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: audit_logs.sql

package db

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs
WHERE tenant_id = $1
`

func (q *Queries) CountAuditLogs(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (
    tenant_id,
    user_id,
    ip_address,
    action,
    resource,
    resource_id,
    before,
    after,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, tenant_id, user_id, ip_address, action, resource, resource_id, before, after, metadata, created_at
`

type CreateAuditLogParams struct {
	TenantID   uuid.UUID        `db:"tenant_id" json:"tenant_id"`
	UserID     *uuid.UUID       `db:"user_id" json:"user_id"`
	IpAddress  *netip.Addr      `db:"ip_address" json:"ip_address"`
	Action     string           `db:"action" json:"action"`
	Resource   *string          `db:"resource" json:"resource"`
	ResourceID *string          `db:"resource_id" json:"resource_id"`
	Before     *json.RawMessage `db:"before" json:"before"`
	After      *json.RawMessage `db:"after" json:"after"`
	Metadata   json.RawMessage  `db:"metadata" json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.TenantID,
		arg.UserID,
		arg.IpAddress,
		arg.Action,
		arg.Resource,
		arg.ResourceID,
		arg.Before,
		arg.After,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.IpAddress,
		&i.Action,
		&i.Resource,
		&i.ResourceID,
		&i.Before,
		&i.After,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldAuditLogs = `-- name: DeleteOldAuditLogs :execresult
DELETE FROM audit_logs
WHERE tenant_id = $1
  AND created_at < $2
`

type DeleteOldAuditLogsParams struct {
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

func (q *Queries) DeleteOldAuditLogs(ctx context.Context, arg DeleteOldAuditLogsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldAuditLogs, arg.TenantID, arg.CreatedAt)
}

const getAuditLogsByTenant = `-- name: GetAuditLogsByTenant :many
SELECT id, tenant_id, user_id, ip_address, action, resource, resource_id, before, after, metadata, created_at FROM audit_logs
WHERE tenant_id = $1
  AND action = $2
ORDER BY created_at DESC
`

type GetAuditLogsByTenantParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Action   string    `db:"action" json:"action"`
}

// Used in tests and admin views — filter by tenant + action without pagination
func (q *Queries) GetAuditLogsByTenant(ctx context.Context, arg GetAuditLogsByTenantParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByTenant, arg.TenantID, arg.Action)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.IpAddress,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Before,
			&i.After,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, tenant_id, user_id, ip_address, action, resource, resource_id, before, after, metadata, created_at FROM audit_logs
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogsParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.IpAddress,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Before,
			&i.After,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsBetween = `-- name: ListAuditLogsBetween :many
SELECT id, tenant_id, user_id, ip_address, action, resource, resource_id, before, after, metadata, created_at FROM audit_logs
WHERE tenant_id = $1
  AND created_at >= $2
  AND created_at <= $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListAuditLogsBetweenParams struct {
	TenantID    uuid.UUID `db:"tenant_id" json:"tenant_id"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	CreatedAt_2 time.Time `db:"created_at_2" json:"created_at_2"`
	Limit       int32     `db:"limit" json:"limit"`
	Offset      int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListAuditLogsBetween(ctx context.Context, arg ListAuditLogsBetweenParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsBetween,
		arg.TenantID,
		arg.CreatedAt,
		arg.CreatedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.IpAddress,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Before,
			&i.After,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByAction = `-- name: ListAuditLogsByAction :many
SELECT id, tenant_id, user_id, ip_address, action, resource, resource_id, before, after, metadata, created_at FROM audit_logs
WHERE tenant_id = $1 AND action = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditLogsByActionParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Action   string    `db:"action" json:"action"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByAction,
		arg.TenantID,
		arg.Action,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.IpAddress,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Before,
			&i.After,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByResource = `-- name: ListAuditLogsByResource :many
SELECT id, tenant_id, user_id, ip_address, action, resource, resource_id, before, after, metadata, created_at FROM audit_logs
WHERE tenant_id = $1 AND resource = $2 AND resource_id = $3
ORDER BY created_at DESC
LIMIT $4
`

type ListAuditLogsByResourceParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Resource   *string   `db:"resource" json:"resource"`
	ResourceID *string   `db:"resource_id" json:"resource_id"`
	Limit      int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByResource,
		arg.TenantID,
		arg.Resource,
		arg.ResourceID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.IpAddress,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Before,
			&i.After,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogsByUser = `-- name: ListAuditLogsByUser :many
SELECT id, tenant_id, user_id, ip_address, action, resource, resource_id, before, after, metadata, created_at FROM audit_logs
WHERE tenant_id = $1 AND user_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditLogsByUserParams struct {
	TenantID uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	UserID   *uuid.UUID `db:"user_id" json:"user_id"`
	Limit    int32      `db:"limit" json:"limit"`
	Offset   int32      `db:"offset" json:"offset"`
}

func (q *Queries) ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogsByUser,
		arg.TenantID,
		arg.UserID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.IpAddress,
			&i.Action,
			&i.Resource,
			&i.ResourceID,
			&i.Before,
			&i.After,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
