// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: billings.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createBillingEvent = `-- name: CreateBillingEvent :one
INSERT INTO billing_events (
    stripe_event_id,
    event_type,
    payload
) VALUES (
    $1, $2, $3
) RETURNING id, stripe_event_id, event_type, payload, processed, processed_at, error, created_at
`

type CreateBillingEventParams struct {
	StripeEventID string          `db:"stripe_event_id" json:"stripe_event_id"`
	EventType     string          `db:"event_type" json:"event_type"`
	Payload       json.RawMessage `db:"payload" json:"payload"`
}

func (q *Queries) CreateBillingEvent(ctx context.Context, arg CreateBillingEventParams) (BillingEvent, error) {
	row := q.db.QueryRow(ctx, createBillingEvent, arg.StripeEventID, arg.EventType, arg.Payload)
	var i BillingEvent
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.Payload,
		&i.Processed,
		&i.ProcessedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    tenant_id,
    stripe_customer_id,
    stripe_subscription_id,
    stripe_price_id,
    plan,
    status,
    current_period_start,
    current_period_end,
    trial_end
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, tenant_id, stripe_customer_id, stripe_subscription_id, stripe_price_id, plan, status, current_period_start, current_period_end, cancel_at_period_end, trial_end, created_at, updated_at
`

type CreateSubscriptionParams struct {
	TenantID             uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	StripeCustomerID     *string    `db:"stripe_customer_id" json:"stripe_customer_id"`
	StripeSubscriptionID *string    `db:"stripe_subscription_id" json:"stripe_subscription_id"`
	StripePriceID        *string    `db:"stripe_price_id" json:"stripe_price_id"`
	Plan                 string     `db:"plan" json:"plan"`
	Status               string     `db:"status" json:"status"`
	CurrentPeriodStart   *time.Time `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd     *time.Time `db:"current_period_end" json:"current_period_end"`
	TrialEnd             *time.Time `db:"trial_end" json:"trial_end"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.TenantID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.StripePriceID,
		arg.Plan,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.TrialEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :exec
DELETE FROM subscriptions
WHERE tenant_id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, tenantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSubscription, tenantID)
	return err
}

const getBillingEventByStripeID = `-- name: GetBillingEventByStripeID :one
SELECT id, stripe_event_id, event_type, payload, processed, processed_at, error, created_at FROM billing_events
WHERE stripe_event_id = $1
LIMIT 1
`

func (q *Queries) GetBillingEventByStripeID(ctx context.Context, stripeEventID string) (BillingEvent, error) {
	row := q.db.QueryRow(ctx, getBillingEventByStripeID, stripeEventID)
	var i BillingEvent
	err := row.Scan(
		&i.ID,
		&i.StripeEventID,
		&i.EventType,
		&i.Payload,
		&i.Processed,
		&i.ProcessedAt,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionByStripeCustomer = `-- name: GetSubscriptionByStripeCustomer :one
SELECT id, tenant_id, stripe_customer_id, stripe_subscription_id, stripe_price_id, plan, status, current_period_start, current_period_end, cancel_at_period_end, trial_end, created_at, updated_at FROM subscriptions
WHERE stripe_customer_id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByStripeCustomer(ctx context.Context, stripeCustomerID *string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeCustomer, stripeCustomerID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByStripeID = `-- name: GetSubscriptionByStripeID :one
SELECT id, tenant_id, stripe_customer_id, stripe_subscription_id, stripe_price_id, plan, status, current_period_start, current_period_end, cancel_at_period_end, trial_end, created_at, updated_at FROM subscriptions
WHERE stripe_subscription_id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByStripeID(ctx context.Context, stripeSubscriptionID *string) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByStripeID, stripeSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubscriptionByTenant = `-- name: GetSubscriptionByTenant :one
SELECT id, tenant_id, stripe_customer_id, stripe_subscription_id, stripe_price_id, plan, status, current_period_start, current_period_end, cancel_at_period_end, trial_end, created_at, updated_at FROM subscriptions
WHERE tenant_id = $1
LIMIT 1
`

func (q *Queries) GetSubscriptionByTenant(ctx context.Context, tenantID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByTenant, tenantID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUnprocessedBillingEvents = `-- name: ListUnprocessedBillingEvents :many
SELECT id, stripe_event_id, event_type, payload, processed, processed_at, error, created_at FROM billing_events
WHERE processed = false
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListUnprocessedBillingEvents(ctx context.Context, limit int32) ([]BillingEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedBillingEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingEvent{}
	for rows.Next() {
		var i BillingEvent
		if err := rows.Scan(
			&i.ID,
			&i.StripeEventID,
			&i.EventType,
			&i.Payload,
			&i.Processed,
			&i.ProcessedAt,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBillingEventFailed = `-- name: MarkBillingEventFailed :exec
UPDATE billing_events
SET
    processed = true,
    processed_at = now(),
    error = $2
WHERE id = $1
`

type MarkBillingEventFailedParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	Error *string   `db:"error" json:"error"`
}

func (q *Queries) MarkBillingEventFailed(ctx context.Context, arg MarkBillingEventFailedParams) error {
	_, err := q.db.Exec(ctx, markBillingEventFailed, arg.ID, arg.Error)
	return err
}

const markBillingEventProcessed = `-- name: MarkBillingEventProcessed :exec
UPDATE billing_events
SET
    processed = true,
    processed_at = now()
WHERE id = $1
`

func (q *Queries) MarkBillingEventProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markBillingEventProcessed, id)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :one
UPDATE subscriptions
SET
    status = $2,
    plan = $3,
    stripe_price_id = $4,
    current_period_start = $5,
    current_period_end = $6,
    cancel_at_period_end = $7,
    updated_at = now()
WHERE tenant_id = $1
RETURNING id, tenant_id, stripe_customer_id, stripe_subscription_id, stripe_price_id, plan, status, current_period_start, current_period_end, cancel_at_period_end, trial_end, created_at, updated_at
`

type UpdateSubscriptionStatusParams struct {
	TenantID           uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	Status             string     `db:"status" json:"status"`
	Plan               string     `db:"plan" json:"plan"`
	StripePriceID      *string    `db:"stripe_price_id" json:"stripe_price_id"`
	CurrentPeriodStart *time.Time `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd   *time.Time `db:"current_period_end" json:"current_period_end"`
	CancelAtPeriodEnd  bool       `db:"cancel_at_period_end" json:"cancel_at_period_end"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionStatus,
		arg.TenantID,
		arg.Status,
		arg.Plan,
		arg.StripePriceID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSubscriptionStripeIDs = `-- name: UpdateSubscriptionStripeIDs :one
UPDATE subscriptions
SET
    stripe_customer_id = $2,
    stripe_subscription_id = $3,
    updated_at = now()
WHERE tenant_id = $1
RETURNING id, tenant_id, stripe_customer_id, stripe_subscription_id, stripe_price_id, plan, status, current_period_start, current_period_end, cancel_at_period_end, trial_end, created_at, updated_at
`

type UpdateSubscriptionStripeIDsParams struct {
	TenantID             uuid.UUID `db:"tenant_id" json:"tenant_id"`
	StripeCustomerID     *string   `db:"stripe_customer_id" json:"stripe_customer_id"`
	StripeSubscriptionID *string   `db:"stripe_subscription_id" json:"stripe_subscription_id"`
}

func (q *Queries) UpdateSubscriptionStripeIDs(ctx context.Context, arg UpdateSubscriptionStripeIDsParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionStripeIDs, arg.TenantID, arg.StripeCustomerID, arg.StripeSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.StripePriceID,
		&i.Plan,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.TrialEnd,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
