// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: enviroments.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkEnvironmentNameExists = `-- name: CheckEnvironmentNameExists :one
SELECT EXISTS(
    SELECT 1 FROM environments
    WHERE tenant_id = $1
      AND name = $2
      AND id != $3
) AS exists
`

type CheckEnvironmentNameExistsParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Name     string    `db:"name" json:"name"`
	ID       uuid.UUID `db:"id" json:"id"`
}

func (q *Queries) CheckEnvironmentNameExists(ctx context.Context, arg CheckEnvironmentNameExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkEnvironmentNameExists, arg.TenantID, arg.Name, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countEnvironmentsByTenant = `-- name: CountEnvironmentsByTenant :one
SELECT count(*) FROM environments
WHERE tenant_id = $1
`

func (q *Queries) CountEnvironmentsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironmentsByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnvironmentsByTenantAndStatus = `-- name: CountEnvironmentsByTenantAndStatus :one
SELECT COUNT(*) FROM environments
WHERE tenant_id = $1
  AND status = $2
`

type CountEnvironmentsByTenantAndStatusParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Status   string    `db:"status" json:"status"`
}

func (q *Queries) CountEnvironmentsByTenantAndStatus(ctx context.Context, arg CountEnvironmentsByTenantAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironmentsByTenantAndStatus, arg.TenantID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnvironmentsByTenantAndType = `-- name: CountEnvironmentsByTenantAndType :one
SELECT COUNT(*) FROM environments
WHERE tenant_id = $1
  AND env_type = $2
`

type CountEnvironmentsByTenantAndTypeParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	EnvType  string    `db:"env_type" json:"env_type"`
}

func (q *Queries) CountEnvironmentsByTenantAndType(ctx context.Context, arg CountEnvironmentsByTenantAndTypeParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironmentsByTenantAndType, arg.TenantID, arg.EnvType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEnvironmentsByTenantTypeAndStatus = `-- name: CountEnvironmentsByTenantTypeAndStatus :one
SELECT COUNT(*) FROM environments
WHERE tenant_id = $1
  AND env_type = $2
  AND status = $3
`

type CountEnvironmentsByTenantTypeAndStatusParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	EnvType  string    `db:"env_type" json:"env_type"`
	Status   string    `db:"status" json:"status"`
}

func (q *Queries) CountEnvironmentsByTenantTypeAndStatus(ctx context.Context, arg CountEnvironmentsByTenantTypeAndStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironmentsByTenantTypeAndStatus, arg.TenantID, arg.EnvType, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnvironment = `-- name: CreateEnvironment :one
INSERT INTO environments (
    tenant_id,
    name,
    odoo_url,
    db_name,
    odoo_version,
    env_type,
    status,
    feature_flags
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, tenant_id, name, odoo_url, db_name, odoo_version, env_type, status, agent_id, feature_flags, last_sync, created_at, updated_at
`

type CreateEnvironmentParams struct {
	TenantID     uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	Name         string          `db:"name" json:"name"`
	OdooUrl      string          `db:"odoo_url" json:"odoo_url"`
	DbName       string          `db:"db_name" json:"db_name"`
	OdooVersion  *string         `db:"odoo_version" json:"odoo_version"`
	EnvType      string          `db:"env_type" json:"env_type"`
	Status       string          `db:"status" json:"status"`
	FeatureFlags json.RawMessage `db:"feature_flags" json:"feature_flags"`
}

func (q *Queries) CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, createEnvironment,
		arg.TenantID,
		arg.Name,
		arg.OdooUrl,
		arg.DbName,
		arg.OdooVersion,
		arg.EnvType,
		arg.Status,
		arg.FeatureFlags,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OdooUrl,
		&i.DbName,
		&i.OdooVersion,
		&i.EnvType,
		&i.Status,
		&i.AgentID,
		&i.FeatureFlags,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvironment = `-- name: DeleteEnvironment :execrows
DELETE FROM environments
WHERE id = $1 AND tenant_id = $2
`

type DeleteEnvironmentParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteEnvironment(ctx context.Context, arg DeleteEnvironmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteEnvironment, arg.ID, arg.TenantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldHeartbeats = `-- name: DeleteOldHeartbeats :execresult
DELETE FROM agent_heartbeats
WHERE env_id IN (
    SELECT id FROM environments WHERE tenant_id = $1
)
AND received_at < $2
`

type DeleteOldHeartbeatsParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	ReceivedAt time.Time `db:"received_at" json:"received_at"`
}

func (q *Queries) DeleteOldHeartbeats(ctx context.Context, arg DeleteOldHeartbeatsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldHeartbeats, arg.TenantID, arg.ReceivedAt)
}

const disconnectAgent = `-- name: DisconnectAgent :exec
UPDATE environments
SET
    status = 'disconnected',
    updated_at = now()
WHERE agent_id = $1
`

func (q *Queries) DisconnectAgent(ctx context.Context, agentID *string) error {
	_, err := q.db.Exec(ctx, disconnectAgent, agentID)
	return err
}

const getEnvironmentByAgentID = `-- name: GetEnvironmentByAgentID :one
SELECT id, tenant_id, name, odoo_url, db_name, odoo_version, env_type, status, agent_id, feature_flags, last_sync, created_at, updated_at FROM environments
WHERE agent_id = $1
LIMIT 1
`

func (q *Queries) GetEnvironmentByAgentID(ctx context.Context, agentID *string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByAgentID, agentID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OdooUrl,
		&i.DbName,
		&i.OdooVersion,
		&i.EnvType,
		&i.Status,
		&i.AgentID,
		&i.FeatureFlags,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironmentByID = `-- name: GetEnvironmentByID :one
SELECT id, tenant_id, name, odoo_url, db_name, odoo_version, env_type, status, agent_id, feature_flags, last_sync, created_at, updated_at FROM environments
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetEnvironmentByIDParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetEnvironmentByID(ctx context.Context, arg GetEnvironmentByIDParams) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByID, arg.ID, arg.TenantID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OdooUrl,
		&i.DbName,
		&i.OdooVersion,
		&i.EnvType,
		&i.Status,
		&i.AgentID,
		&i.FeatureFlags,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFeatureFlags = `-- name: GetFeatureFlags :one
SELECT feature_flags FROM environments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetFeatureFlags(ctx context.Context, id uuid.UUID) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, getFeatureFlags, id)
	var feature_flags json.RawMessage
	err := row.Scan(&feature_flags)
	return feature_flags, err
}

const getLatestHeartbeat = `-- name: GetLatestHeartbeat :one
SELECT id, env_id, agent_id, agent_version, status, metadata, received_at FROM agent_heartbeats
WHERE env_id = $1
ORDER BY received_at DESC
LIMIT 1
`

func (q *Queries) GetLatestHeartbeat(ctx context.Context, envID uuid.UUID) (AgentHeartbeat, error) {
	row := q.db.QueryRow(ctx, getLatestHeartbeat, envID)
	var i AgentHeartbeat
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.AgentID,
		&i.AgentVersion,
		&i.Status,
		&i.Metadata,
		&i.ReceivedAt,
	)
	return i, err
}

const insertHeartbeat = `-- name: InsertHeartbeat :one

INSERT INTO agent_heartbeats (
    env_id,
    agent_id,
    agent_version,
    status,
    metadata
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, env_id, agent_id, agent_version, status, metadata, received_at
`

type InsertHeartbeatParams struct {
	EnvID        uuid.UUID       `db:"env_id" json:"env_id"`
	AgentID      string          `db:"agent_id" json:"agent_id"`
	AgentVersion *string         `db:"agent_version" json:"agent_version"`
	Status       string          `db:"status" json:"status"`
	Metadata     json.RawMessage `db:"metadata" json:"metadata"`
}

// ════════════════════════════════════════════
//
//	Agent Heartbeats
//
// ════════════════════════════════════════════
func (q *Queries) InsertHeartbeat(ctx context.Context, arg InsertHeartbeatParams) (AgentHeartbeat, error) {
	row := q.db.QueryRow(ctx, insertHeartbeat,
		arg.EnvID,
		arg.AgentID,
		arg.AgentVersion,
		arg.Status,
		arg.Metadata,
	)
	var i AgentHeartbeat
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.AgentID,
		&i.AgentVersion,
		&i.Status,
		&i.Metadata,
		&i.ReceivedAt,
	)
	return i, err
}

const listEnvironmentsByTenant = `-- name: ListEnvironmentsByTenant :many
SELECT id, tenant_id, name, odoo_url, db_name, odoo_version, env_type, status, agent_id, feature_flags, last_sync, created_at, updated_at FROM environments
WHERE tenant_id = $1
ORDER BY created_at
`

func (q *Queries) ListEnvironmentsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.OdooUrl,
			&i.DbName,
			&i.OdooVersion,
			&i.EnvType,
			&i.Status,
			&i.AgentID,
			&i.FeatureFlags,
			&i.LastSync,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsByTenantAndStatus = `-- name: ListEnvironmentsByTenantAndStatus :many
SELECT id, tenant_id, name, odoo_url, db_name, odoo_version, env_type, status, agent_id, feature_flags, last_sync, created_at, updated_at FROM environments
WHERE tenant_id = $1
  AND status = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListEnvironmentsByTenantAndStatusParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Status   string    `db:"status" json:"status"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListEnvironmentsByTenantAndStatus(ctx context.Context, arg ListEnvironmentsByTenantAndStatusParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByTenantAndStatus,
		arg.TenantID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.OdooUrl,
			&i.DbName,
			&i.OdooVersion,
			&i.EnvType,
			&i.Status,
			&i.AgentID,
			&i.FeatureFlags,
			&i.LastSync,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsByTenantAndType = `-- name: ListEnvironmentsByTenantAndType :many
SELECT id, tenant_id, name, odoo_url, db_name, odoo_version, env_type, status, agent_id, feature_flags, last_sync, created_at, updated_at FROM environments
WHERE tenant_id = $1
  AND env_type = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListEnvironmentsByTenantAndTypeParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	EnvType  string    `db:"env_type" json:"env_type"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListEnvironmentsByTenantAndType(ctx context.Context, arg ListEnvironmentsByTenantAndTypeParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByTenantAndType,
		arg.TenantID,
		arg.EnvType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.OdooUrl,
			&i.DbName,
			&i.OdooVersion,
			&i.EnvType,
			&i.Status,
			&i.AgentID,
			&i.FeatureFlags,
			&i.LastSync,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnvironmentsByTenantTypeAndStatus = `-- name: ListEnvironmentsByTenantTypeAndStatus :many
SELECT id, tenant_id, name, odoo_url, db_name, odoo_version, env_type, status, agent_id, feature_flags, last_sync, created_at, updated_at FROM environments
WHERE tenant_id = $1
  AND env_type = $2
  AND status = $3
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListEnvironmentsByTenantTypeAndStatusParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	EnvType  string    `db:"env_type" json:"env_type"`
	Status   string    `db:"status" json:"status"`
	Limit    int32     `db:"limit" json:"limit"`
	Offset   int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListEnvironmentsByTenantTypeAndStatus(ctx context.Context, arg ListEnvironmentsByTenantTypeAndStatusParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironmentsByTenantTypeAndStatus,
		arg.TenantID,
		arg.EnvType,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Environment{}
	for rows.Next() {
		var i Environment
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.OdooUrl,
			&i.DbName,
			&i.OdooVersion,
			&i.EnvType,
			&i.Status,
			&i.AgentID,
			&i.FeatureFlags,
			&i.LastSync,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHeartbeats = `-- name: ListHeartbeats :many
SELECT id, env_id, agent_id, agent_version, status, metadata, received_at FROM agent_heartbeats
WHERE env_id = $1
ORDER BY received_at DESC
LIMIT $2
`

type ListHeartbeatsParams struct {
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
	Limit int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListHeartbeats(ctx context.Context, arg ListHeartbeatsParams) ([]AgentHeartbeat, error) {
	rows, err := q.db.Query(ctx, listHeartbeats, arg.EnvID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentHeartbeat{}
	for rows.Next() {
		var i AgentHeartbeat
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.AgentID,
			&i.AgentVersion,
			&i.Status,
			&i.Metadata,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleAgents = `-- name: ListStaleAgents :many
SELECT e.id AS env_id, e.name, e.agent_id, e.tenant_id,
       COALESCE(h.received_at, '1970-01-01'::timestamptz) AS last_heartbeat
FROM environments e
LEFT JOIN LATERAL (
    SELECT received_at FROM agent_heartbeats
    WHERE env_id = e.id
    ORDER BY received_at DESC LIMIT 1
) h ON true
WHERE e.status = 'connected'
  AND (h.received_at IS NULL OR h.received_at < now() - $1::interval)
`

type ListStaleAgentsRow struct {
	EnvID         uuid.UUID `db:"env_id" json:"env_id"`
	Name          string    `db:"name" json:"name"`
	AgentID       *string   `db:"agent_id" json:"agent_id"`
	TenantID      uuid.UUID `db:"tenant_id" json:"tenant_id"`
	LastHeartbeat time.Time `db:"last_heartbeat" json:"last_heartbeat"`
}

func (q *Queries) ListStaleAgents(ctx context.Context, dollar_1 pgtype.Interval) ([]ListStaleAgentsRow, error) {
	rows, err := q.db.Query(ctx, listStaleAgents, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleAgentsRow{}
	for rows.Next() {
		var i ListStaleAgentsRow
		if err := rows.Scan(
			&i.EnvID,
			&i.Name,
			&i.AgentID,
			&i.TenantID,
			&i.LastHeartbeat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerAgent = `-- name: RegisterAgent :one
UPDATE environments
SET
    agent_id = $2,
    status = 'connected',
    last_sync = now(),
    updated_at = now()
WHERE id = $1 AND tenant_id = $3
RETURNING id, tenant_id, name, odoo_url, db_name, odoo_version, env_type, status, agent_id, feature_flags, last_sync, created_at, updated_at
`

type RegisterAgentParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	AgentID  *string   `db:"agent_id" json:"agent_id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) RegisterAgent(ctx context.Context, arg RegisterAgentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, registerAgent, arg.ID, arg.AgentID, arg.TenantID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OdooUrl,
		&i.DbName,
		&i.OdooVersion,
		&i.EnvType,
		&i.Status,
		&i.AgentID,
		&i.FeatureFlags,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEnvironment = `-- name: UpdateEnvironment :one
UPDATE environments
SET
    name          = COALESCE($3, name),
    odoo_url      = COALESCE($4, odoo_url),
    db_name       = COALESCE($5, db_name),
    odoo_version  = COALESCE($6, odoo_version),
    env_type      = COALESCE($7, env_type),
    status        = COALESCE($8, status),
    feature_flags = COALESCE($9, feature_flags),
    updated_at    = NOW()
WHERE id = $1 AND tenant_id = $2
RETURNING id, tenant_id, name, odoo_url, db_name, odoo_version, env_type, status, agent_id, feature_flags, last_sync, created_at, updated_at
`

type UpdateEnvironmentParams struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	TenantID     uuid.UUID        `db:"tenant_id" json:"tenant_id"`
	Name         *string          `db:"name" json:"name"`
	OdooUrl      *string          `db:"odoo_url" json:"odoo_url"`
	DbName       *string          `db:"db_name" json:"db_name"`
	OdooVersion  *string          `db:"odoo_version" json:"odoo_version"`
	EnvType      *string          `db:"env_type" json:"env_type"`
	Status       *string          `db:"status" json:"status"`
	FeatureFlags *json.RawMessage `db:"feature_flags" json:"feature_flags"`
}

func (q *Queries) UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateEnvironment,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.OdooUrl,
		arg.DbName,
		arg.OdooVersion,
		arg.EnvType,
		arg.Status,
		arg.FeatureFlags,
	)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OdooUrl,
		&i.DbName,
		&i.OdooVersion,
		&i.EnvType,
		&i.Status,
		&i.AgentID,
		&i.FeatureFlags,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEnvironmentStatus = `-- name: UpdateEnvironmentStatus :exec
UPDATE environments
SET
    status = $2,
    last_sync = now(),
    updated_at = now()
WHERE id = $1
`

type UpdateEnvironmentStatusParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) UpdateEnvironmentStatus(ctx context.Context, arg UpdateEnvironmentStatusParams) error {
	_, err := q.db.Exec(ctx, updateEnvironmentStatus, arg.ID, arg.Status)
	return err
}

const updateFeatureFlags = `-- name: UpdateFeatureFlags :one
UPDATE environments
SET
    feature_flags = $2,
    updated_at = now()
WHERE id = $1 AND tenant_id = $3
RETURNING id, tenant_id, name, odoo_url, db_name, odoo_version, env_type, status, agent_id, feature_flags, last_sync, created_at, updated_at
`

type UpdateFeatureFlagsParams struct {
	ID           uuid.UUID       `db:"id" json:"id"`
	FeatureFlags json.RawMessage `db:"feature_flags" json:"feature_flags"`
	TenantID     uuid.UUID       `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) UpdateFeatureFlags(ctx context.Context, arg UpdateFeatureFlagsParams) (Environment, error) {
	row := q.db.QueryRow(ctx, updateFeatureFlags, arg.ID, arg.FeatureFlags, arg.TenantID)
	var i Environment
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.OdooUrl,
		&i.DbName,
		&i.OdooVersion,
		&i.EnvType,
		&i.Status,
		&i.AgentID,
		&i.FeatureFlags,
		&i.LastSync,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
