// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: error_groups.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const acknowledgeErrorGroup = `-- name: AcknowledgeErrorGroup :one
UPDATE error_groups
SET status = 'acknowledged'
WHERE id = $1 AND env_id = $2
RETURNING id, env_id, signature, error_type, message, module, model, first_seen, last_seen, occurrence_count, affected_users, status, resolved_by, resolved_at, raw_trace_ref, created_at
`

type AcknowledgeErrorGroupParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
}

func (q *Queries) AcknowledgeErrorGroup(ctx context.Context, arg AcknowledgeErrorGroupParams) (ErrorGroup, error) {
	row := q.db.QueryRow(ctx, acknowledgeErrorGroup, arg.ID, arg.EnvID)
	var i ErrorGroup
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Signature,
		&i.ErrorType,
		&i.Message,
		&i.Module,
		&i.Model,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.AffectedUsers,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.RawTraceRef,
		&i.CreatedAt,
	)
	return i, err
}

const appendAffectedUsers = `-- name: AppendAffectedUsers :exec
UPDATE error_groups
SET affected_users = (
    SELECT array_agg(DISTINCT u)
    FROM unnest(affected_users || $1::int[]) u
)
WHERE id = $2
`

type AppendAffectedUsersParams struct {
	UserIds []int32   `db:"user_ids" json:"user_ids"`
	ID      uuid.UUID `db:"id" json:"id"`
}

// Merge new user IDs into the existing array (deduplicated)
func (q *Queries) AppendAffectedUsers(ctx context.Context, arg AppendAffectedUsersParams) error {
	_, err := q.db.Exec(ctx, appendAffectedUsers, arg.UserIds, arg.ID)
	return err
}

const countErrorGroupsByEnv = `-- name: CountErrorGroupsByEnv :one
SELECT count(*) FROM error_groups
WHERE env_id = $1
`

func (q *Queries) CountErrorGroupsByEnv(ctx context.Context, envID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countErrorGroupsByEnv, envID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countErrorGroupsByStatus = `-- name: CountErrorGroupsByStatus :one
SELECT count(*) FROM error_groups
WHERE env_id = $1 AND status = $2
`

type CountErrorGroupsByStatusParams struct {
	EnvID  uuid.UUID `db:"env_id" json:"env_id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) CountErrorGroupsByStatus(ctx context.Context, arg CountErrorGroupsByStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, countErrorGroupsByStatus, arg.EnvID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldErrorGroups = `-- name: DeleteOldErrorGroups :execresult
DELETE FROM error_groups
WHERE env_id IN (
    SELECT id FROM environments WHERE tenant_id = $1
)
AND last_seen < $2
AND status != 'open'
`

type DeleteOldErrorGroupsParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	LastSeen time.Time `db:"last_seen" json:"last_seen"`
}

func (q *Queries) DeleteOldErrorGroups(ctx context.Context, arg DeleteOldErrorGroupsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldErrorGroups, arg.TenantID, arg.LastSeen)
}

const getErrorGroupByID = `-- name: GetErrorGroupByID :one
SELECT id, env_id, signature, error_type, message, module, model, first_seen, last_seen, occurrence_count, affected_users, status, resolved_by, resolved_at, raw_trace_ref, created_at FROM error_groups
WHERE id = $1 AND env_id = $2
LIMIT 1
`

type GetErrorGroupByIDParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
}

func (q *Queries) GetErrorGroupByID(ctx context.Context, arg GetErrorGroupByIDParams) (ErrorGroup, error) {
	row := q.db.QueryRow(ctx, getErrorGroupByID, arg.ID, arg.EnvID)
	var i ErrorGroup
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Signature,
		&i.ErrorType,
		&i.Message,
		&i.Module,
		&i.Model,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.AffectedUsers,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.RawTraceRef,
		&i.CreatedAt,
	)
	return i, err
}

const getErrorGroupBySignature = `-- name: GetErrorGroupBySignature :one
SELECT id, env_id, signature, error_type, message, module, model, first_seen, last_seen, occurrence_count, affected_users, status, resolved_by, resolved_at, raw_trace_ref, created_at FROM error_groups
WHERE env_id = $1 AND signature = $2
LIMIT 1
`

type GetErrorGroupBySignatureParams struct {
	EnvID     uuid.UUID `db:"env_id" json:"env_id"`
	Signature string    `db:"signature" json:"signature"`
}

func (q *Queries) GetErrorGroupBySignature(ctx context.Context, arg GetErrorGroupBySignatureParams) (ErrorGroup, error) {
	row := q.db.QueryRow(ctx, getErrorGroupBySignature, arg.EnvID, arg.Signature)
	var i ErrorGroup
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Signature,
		&i.ErrorType,
		&i.Message,
		&i.Module,
		&i.Model,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.AffectedUsers,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.RawTraceRef,
		&i.CreatedAt,
	)
	return i, err
}

const listErrorGroups = `-- name: ListErrorGroups :many
SELECT id, env_id, signature, error_type, message, module, model, first_seen, last_seen, occurrence_count, affected_users, status, resolved_by, resolved_at, raw_trace_ref, created_at FROM error_groups
WHERE env_id = $1
ORDER BY occurrence_count DESC, last_seen DESC
LIMIT $2 OFFSET $3
`

type ListErrorGroupsParams struct {
	EnvID  uuid.UUID `db:"env_id" json:"env_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListErrorGroups(ctx context.Context, arg ListErrorGroupsParams) ([]ErrorGroup, error) {
	rows, err := q.db.Query(ctx, listErrorGroups, arg.EnvID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorGroup{}
	for rows.Next() {
		var i ErrorGroup
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Signature,
			&i.ErrorType,
			&i.Message,
			&i.Module,
			&i.Model,
			&i.FirstSeen,
			&i.LastSeen,
			&i.OccurrenceCount,
			&i.AffectedUsers,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.RawTraceRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorGroupsByStatus = `-- name: ListErrorGroupsByStatus :many
SELECT id, env_id, signature, error_type, message, module, model, first_seen, last_seen, occurrence_count, affected_users, status, resolved_by, resolved_at, raw_trace_ref, created_at FROM error_groups
WHERE env_id = $1 AND status = $2
ORDER BY last_seen DESC
LIMIT $3 OFFSET $4
`

type ListErrorGroupsByStatusParams struct {
	EnvID  uuid.UUID `db:"env_id" json:"env_id"`
	Status string    `db:"status" json:"status"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListErrorGroupsByStatus(ctx context.Context, arg ListErrorGroupsByStatusParams) ([]ErrorGroup, error) {
	rows, err := q.db.Query(ctx, listErrorGroupsByStatus,
		arg.EnvID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorGroup{}
	for rows.Next() {
		var i ErrorGroup
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Signature,
			&i.ErrorType,
			&i.Message,
			&i.Module,
			&i.Model,
			&i.FirstSeen,
			&i.LastSeen,
			&i.OccurrenceCount,
			&i.AffectedUsers,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.RawTraceRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorGroupsByType = `-- name: ListErrorGroupsByType :many
SELECT id, env_id, signature, error_type, message, module, model, first_seen, last_seen, occurrence_count, affected_users, status, resolved_by, resolved_at, raw_trace_ref, created_at FROM error_groups
WHERE env_id = $1 AND error_type = $2
ORDER BY occurrence_count DESC
LIMIT $3 OFFSET $4
`

type ListErrorGroupsByTypeParams struct {
	EnvID     uuid.UUID `db:"env_id" json:"env_id"`
	ErrorType string    `db:"error_type" json:"error_type"`
	Limit     int32     `db:"limit" json:"limit"`
	Offset    int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListErrorGroupsByType(ctx context.Context, arg ListErrorGroupsByTypeParams) ([]ErrorGroup, error) {
	rows, err := q.db.Query(ctx, listErrorGroupsByType,
		arg.EnvID,
		arg.ErrorType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorGroup{}
	for rows.Next() {
		var i ErrorGroup
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Signature,
			&i.ErrorType,
			&i.Message,
			&i.Module,
			&i.Model,
			&i.FirstSeen,
			&i.LastSeen,
			&i.OccurrenceCount,
			&i.AffectedUsers,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.RawTraceRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reopenErrorGroup = `-- name: ReopenErrorGroup :one
UPDATE error_groups
SET
    status = 'open',
    resolved_by = NULL,
    resolved_at = NULL
WHERE id = $1 AND env_id = $2
RETURNING id, env_id, signature, error_type, message, module, model, first_seen, last_seen, occurrence_count, affected_users, status, resolved_by, resolved_at, raw_trace_ref, created_at
`

type ReopenErrorGroupParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
}

func (q *Queries) ReopenErrorGroup(ctx context.Context, arg ReopenErrorGroupParams) (ErrorGroup, error) {
	row := q.db.QueryRow(ctx, reopenErrorGroup, arg.ID, arg.EnvID)
	var i ErrorGroup
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Signature,
		&i.ErrorType,
		&i.Message,
		&i.Module,
		&i.Model,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.AffectedUsers,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.RawTraceRef,
		&i.CreatedAt,
	)
	return i, err
}

const resolveErrorGroup = `-- name: ResolveErrorGroup :one
UPDATE error_groups
SET
    status = 'resolved',
    resolved_by = $2,
    resolved_at = now()
WHERE id = $1 AND env_id = $3
RETURNING id, env_id, signature, error_type, message, module, model, first_seen, last_seen, occurrence_count, affected_users, status, resolved_by, resolved_at, raw_trace_ref, created_at
`

type ResolveErrorGroupParams struct {
	ID         uuid.UUID  `db:"id" json:"id"`
	ResolvedBy *uuid.UUID `db:"resolved_by" json:"resolved_by"`
	EnvID      uuid.UUID  `db:"env_id" json:"env_id"`
}

func (q *Queries) ResolveErrorGroup(ctx context.Context, arg ResolveErrorGroupParams) (ErrorGroup, error) {
	row := q.db.QueryRow(ctx, resolveErrorGroup, arg.ID, arg.ResolvedBy, arg.EnvID)
	var i ErrorGroup
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Signature,
		&i.ErrorType,
		&i.Message,
		&i.Module,
		&i.Model,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.AffectedUsers,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.RawTraceRef,
		&i.CreatedAt,
	)
	return i, err
}

const searchErrorGroups = `-- name: SearchErrorGroups :many
SELECT id, env_id, signature, error_type, message, module, model, first_seen, last_seen, occurrence_count, affected_users, status, resolved_by, resolved_at, raw_trace_ref, created_at FROM error_groups
WHERE env_id = $1
  AND (message ILIKE '%' || $2 || '%' OR module ILIKE '%' || $2 || '%' OR model ILIKE '%' || $2 || '%')
ORDER BY last_seen DESC
LIMIT $3 OFFSET $4
`

type SearchErrorGroupsParams struct {
	EnvID   uuid.UUID `db:"env_id" json:"env_id"`
	Column2 *string   `db:"column_2" json:"column_2"`
	Limit   int32     `db:"limit" json:"limit"`
	Offset  int32     `db:"offset" json:"offset"`
}

func (q *Queries) SearchErrorGroups(ctx context.Context, arg SearchErrorGroupsParams) ([]ErrorGroup, error) {
	rows, err := q.db.Query(ctx, searchErrorGroups,
		arg.EnvID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ErrorGroup{}
	for rows.Next() {
		var i ErrorGroup
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Signature,
			&i.ErrorType,
			&i.Message,
			&i.Module,
			&i.Model,
			&i.FirstSeen,
			&i.LastSeen,
			&i.OccurrenceCount,
			&i.AffectedUsers,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.RawTraceRef,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertErrorGroup = `-- name: UpsertErrorGroup :one
INSERT INTO error_groups (
    env_id,
    signature,
    error_type,
    message,
    module,
    model,
    first_seen,
    last_seen,
    occurrence_count,
    affected_users,
    raw_trace_ref
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $7, 1, $8, $9
)
ON CONFLICT (env_id, signature) DO UPDATE SET
    last_seen        = EXCLUDED.last_seen,
    occurrence_count = error_groups.occurrence_count + 1,
    raw_trace_ref    = EXCLUDED.raw_trace_ref,
    message          = EXCLUDED.message,
    -- auto-reopen: if the error fires again after being resolved/acknowledged,
    -- reset back to open so a false-resolve doesn't hide recurring issues
    status           = CASE WHEN error_groups.status IN ('resolved', 'acknowledged') THEN 'open' ELSE error_groups.status END,
    resolved_by      = CASE WHEN error_groups.status IN ('resolved', 'acknowledged') THEN NULL ELSE error_groups.resolved_by END,
    resolved_at      = CASE WHEN error_groups.status IN ('resolved', 'acknowledged') THEN NULL ELSE error_groups.resolved_at END
RETURNING id, env_id, signature, error_type, message, module, model, first_seen, last_seen, occurrence_count, affected_users, status, resolved_by, resolved_at, raw_trace_ref, created_at
`

type UpsertErrorGroupParams struct {
	EnvID         uuid.UUID `db:"env_id" json:"env_id"`
	Signature     string    `db:"signature" json:"signature"`
	ErrorType     string    `db:"error_type" json:"error_type"`
	Message       string    `db:"message" json:"message"`
	Module        *string   `db:"module" json:"module"`
	Model         *string   `db:"model" json:"model"`
	FirstSeen     time.Time `db:"first_seen" json:"first_seen"`
	AffectedUsers []int32   `db:"affected_users" json:"affected_users"`
	RawTraceRef   *string   `db:"raw_trace_ref" json:"raw_trace_ref"`
}

func (q *Queries) UpsertErrorGroup(ctx context.Context, arg UpsertErrorGroupParams) (ErrorGroup, error) {
	row := q.db.QueryRow(ctx, upsertErrorGroup,
		arg.EnvID,
		arg.Signature,
		arg.ErrorType,
		arg.Message,
		arg.Module,
		arg.Model,
		arg.FirstSeen,
		arg.AffectedUsers,
		arg.RawTraceRef,
	)
	var i ErrorGroup
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Signature,
		&i.ErrorType,
		&i.Message,
		&i.Module,
		&i.Model,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.AffectedUsers,
		&i.Status,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.RawTraceRef,
		&i.CreatedAt,
	)
	return i, err
}
