// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: migrations_scan.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createMigrationScan = `-- name: CreateMigrationScan :one
INSERT INTO migration_scans (
    env_id,
    triggered_by,
    from_version,
    to_version,
    issues,
    breaking_count,
    warning_count,
    minor_count,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, env_id, triggered_by, from_version, to_version, issues, breaking_count, warning_count, minor_count, status, scanned_at
`

type CreateMigrationScanParams struct {
	EnvID         uuid.UUID       `db:"env_id" json:"env_id"`
	TriggeredBy   *uuid.UUID      `db:"triggered_by" json:"triggered_by"`
	FromVersion   string          `db:"from_version" json:"from_version"`
	ToVersion     string          `db:"to_version" json:"to_version"`
	Issues        json.RawMessage `db:"issues" json:"issues"`
	BreakingCount int32           `db:"breaking_count" json:"breaking_count"`
	WarningCount  int32           `db:"warning_count" json:"warning_count"`
	MinorCount    int32           `db:"minor_count" json:"minor_count"`
	Status        string          `db:"status" json:"status"`
}

func (q *Queries) CreateMigrationScan(ctx context.Context, arg CreateMigrationScanParams) (MigrationScan, error) {
	row := q.db.QueryRow(ctx, createMigrationScan,
		arg.EnvID,
		arg.TriggeredBy,
		arg.FromVersion,
		arg.ToVersion,
		arg.Issues,
		arg.BreakingCount,
		arg.WarningCount,
		arg.MinorCount,
		arg.Status,
	)
	var i MigrationScan
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.TriggeredBy,
		&i.FromVersion,
		&i.ToVersion,
		&i.Issues,
		&i.BreakingCount,
		&i.WarningCount,
		&i.MinorCount,
		&i.Status,
		&i.ScannedAt,
	)
	return i, err
}

const deleteMigrationScan = `-- name: DeleteMigrationScan :exec
DELETE FROM migration_scans
WHERE id = $1 AND env_id = $2
`

type DeleteMigrationScanParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
}

func (q *Queries) DeleteMigrationScan(ctx context.Context, arg DeleteMigrationScanParams) error {
	_, err := q.db.Exec(ctx, deleteMigrationScan, arg.ID, arg.EnvID)
	return err
}

const getLatestMigrationScan = `-- name: GetLatestMigrationScan :one
SELECT id, env_id, triggered_by, from_version, to_version, issues, breaking_count, warning_count, minor_count, status, scanned_at FROM migration_scans
WHERE env_id = $1
ORDER BY scanned_at DESC
LIMIT 1
`

func (q *Queries) GetLatestMigrationScan(ctx context.Context, envID uuid.UUID) (MigrationScan, error) {
	row := q.db.QueryRow(ctx, getLatestMigrationScan, envID)
	var i MigrationScan
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.TriggeredBy,
		&i.FromVersion,
		&i.ToVersion,
		&i.Issues,
		&i.BreakingCount,
		&i.WarningCount,
		&i.MinorCount,
		&i.Status,
		&i.ScannedAt,
	)
	return i, err
}

const getMigrationScan = `-- name: GetMigrationScan :one
SELECT id, env_id, triggered_by, from_version, to_version, issues, breaking_count, warning_count, minor_count, status, scanned_at FROM migration_scans
WHERE id = $1 AND env_id = $2
LIMIT 1
`

type GetMigrationScanParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
}

func (q *Queries) GetMigrationScan(ctx context.Context, arg GetMigrationScanParams) (MigrationScan, error) {
	row := q.db.QueryRow(ctx, getMigrationScan, arg.ID, arg.EnvID)
	var i MigrationScan
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.TriggeredBy,
		&i.FromVersion,
		&i.ToVersion,
		&i.Issues,
		&i.BreakingCount,
		&i.WarningCount,
		&i.MinorCount,
		&i.Status,
		&i.ScannedAt,
	)
	return i, err
}

const listMigrationScans = `-- name: ListMigrationScans :many
SELECT id, env_id, triggered_by, from_version, to_version, issues, breaking_count, warning_count, minor_count, status, scanned_at FROM migration_scans
WHERE env_id = $1
ORDER BY scanned_at DESC
LIMIT $2 OFFSET $3
`

type ListMigrationScansParams struct {
	EnvID  uuid.UUID `db:"env_id" json:"env_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListMigrationScans(ctx context.Context, arg ListMigrationScansParams) ([]MigrationScan, error) {
	rows, err := q.db.Query(ctx, listMigrationScans, arg.EnvID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MigrationScan{}
	for rows.Next() {
		var i MigrationScan
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.TriggeredBy,
			&i.FromVersion,
			&i.ToVersion,
			&i.Issues,
			&i.BreakingCount,
			&i.WarningCount,
			&i.MinorCount,
			&i.Status,
			&i.ScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
