// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AgentHeartbeat struct {
	ID           uuid.UUID       `db:"id" json:"id"`
	EnvID        uuid.UUID       `db:"env_id" json:"env_id"`
	AgentID      string          `db:"agent_id" json:"agent_id"`
	AgentVersion *string         `db:"agent_version" json:"agent_version"`
	Status       string          `db:"status" json:"status"`
	Metadata     json.RawMessage `db:"metadata" json:"metadata"`
	ReceivedAt   time.Time       `db:"received_at" json:"received_at"`
}

type Alert struct {
	ID             uuid.UUID       `db:"id" json:"id"`
	EnvID          uuid.UUID       `db:"env_id" json:"env_id"`
	Type           string          `db:"type" json:"type"`
	Severity       string          `db:"severity" json:"severity"`
	Message        string          `db:"message" json:"message"`
	Metadata       json.RawMessage `db:"metadata" json:"metadata"`
	Acknowledged   bool            `db:"acknowledged" json:"acknowledged"`
	AcknowledgedBy *uuid.UUID      `db:"acknowledged_by" json:"acknowledged_by"`
	AcknowledgedAt *time.Time      `db:"acknowledged_at" json:"acknowledged_at"`
	CreatedAt      time.Time       `db:"created_at" json:"created_at"`
}

type AlertDelivery struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	AlertID   uuid.UUID  `db:"alert_id" json:"alert_id"`
	ChannelID uuid.UUID  `db:"channel_id" json:"channel_id"`
	Status    string     `db:"status" json:"status"`
	Attempt   int32      `db:"attempt" json:"attempt"`
	Error     *string    `db:"error" json:"error"`
	SentAt    *time.Time `db:"sent_at" json:"sent_at"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
}

type AnonProfile struct {
	ID         uuid.UUID       `db:"id" json:"id"`
	TenantID   uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	CreatedBy  *uuid.UUID      `db:"created_by" json:"created_by"`
	Name       string          `db:"name" json:"name"`
	SourceEnv  *uuid.UUID      `db:"source_env" json:"source_env"`
	TargetEnv  *uuid.UUID      `db:"target_env" json:"target_env"`
	FieldRules json.RawMessage `db:"field_rules" json:"field_rules"`
	Status     string          `db:"status" json:"status"`
	LastRun    *time.Time      `db:"last_run" json:"last_run"`
	LastRunBy  *uuid.UUID      `db:"last_run_by" json:"last_run_by"`
	AuditRef   *string         `db:"audit_ref" json:"audit_ref"`
	CreatedAt  time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time       `db:"updated_at" json:"updated_at"`
}

type ApiKey struct {
	ID        uuid.UUID  `db:"id" json:"id"`
	TenantID  uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	CreatedBy *uuid.UUID `db:"created_by" json:"created_by"`
	KeyHash   string     `db:"key_hash" json:"key_hash"`
	KeyPrefix string     `db:"key_prefix" json:"key_prefix"`
	Name      string     `db:"name" json:"name"`
	Scopes    []string   `db:"scopes" json:"scopes"`
	LastUsed  *time.Time `db:"last_used" json:"last_used"`
	ExpiresAt *time.Time `db:"expires_at" json:"expires_at"`
	IsActive  bool       `db:"is_active" json:"is_active"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
}

type AuditLog struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	TenantID   uuid.UUID        `db:"tenant_id" json:"tenant_id"`
	UserID     *uuid.UUID       `db:"user_id" json:"user_id"`
	IpAddress  *netip.Addr      `db:"ip_address" json:"ip_address"`
	Action     string           `db:"action" json:"action"`
	Resource   *string          `db:"resource" json:"resource"`
	ResourceID *string          `db:"resource_id" json:"resource_id"`
	Before     *json.RawMessage `db:"before" json:"before"`
	After      *json.RawMessage `db:"after" json:"after"`
	Metadata   json.RawMessage  `db:"metadata" json:"metadata"`
	CreatedAt  time.Time        `db:"created_at" json:"created_at"`
}

type BillingEvent struct {
	ID            uuid.UUID       `db:"id" json:"id"`
	StripeEventID string          `db:"stripe_event_id" json:"stripe_event_id"`
	EventType     string          `db:"event_type" json:"event_type"`
	Payload       json.RawMessage `db:"payload" json:"payload"`
	Processed     bool            `db:"processed" json:"processed"`
	ProcessedAt   *time.Time      `db:"processed_at" json:"processed_at"`
	Error         *string         `db:"error" json:"error"`
	CreatedAt     time.Time       `db:"created_at" json:"created_at"`
}

type Environment struct {
	ID           uuid.UUID       `db:"id" json:"id"`
	TenantID     uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	Name         string          `db:"name" json:"name"`
	OdooUrl      string          `db:"odoo_url" json:"odoo_url"`
	DbName       string          `db:"db_name" json:"db_name"`
	OdooVersion  *string         `db:"odoo_version" json:"odoo_version"`
	EnvType      string          `db:"env_type" json:"env_type"`
	Status       string          `db:"status" json:"status"`
	AgentID      *string         `db:"agent_id" json:"agent_id"`
	FeatureFlags json.RawMessage `db:"feature_flags" json:"feature_flags"`
	LastSync     *time.Time      `db:"last_sync" json:"last_sync"`
	CreatedAt    time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time       `db:"updated_at" json:"updated_at"`
}

type ErrorGroup struct {
	ID              uuid.UUID  `db:"id" json:"id"`
	EnvID           uuid.UUID  `db:"env_id" json:"env_id"`
	Signature       string     `db:"signature" json:"signature"`
	ErrorType       string     `db:"error_type" json:"error_type"`
	Message         string     `db:"message" json:"message"`
	Module          *string    `db:"module" json:"module"`
	Model           *string    `db:"model" json:"model"`
	FirstSeen       time.Time  `db:"first_seen" json:"first_seen"`
	LastSeen        time.Time  `db:"last_seen" json:"last_seen"`
	OccurrenceCount int32      `db:"occurrence_count" json:"occurrence_count"`
	AffectedUsers   []int32    `db:"affected_users" json:"affected_users"`
	Status          string     `db:"status" json:"status"`
	ResolvedBy      *uuid.UUID `db:"resolved_by" json:"resolved_by"`
	ResolvedAt      *time.Time `db:"resolved_at" json:"resolved_at"`
	RawTraceRef     *string    `db:"raw_trace_ref" json:"raw_trace_ref"`
	CreatedAt       time.Time  `db:"created_at" json:"created_at"`
}

type MigrationScan struct {
	ID            uuid.UUID       `db:"id" json:"id"`
	EnvID         uuid.UUID       `db:"env_id" json:"env_id"`
	TriggeredBy   *uuid.UUID      `db:"triggered_by" json:"triggered_by"`
	FromVersion   string          `db:"from_version" json:"from_version"`
	ToVersion     string          `db:"to_version" json:"to_version"`
	Issues        json.RawMessage `db:"issues" json:"issues"`
	BreakingCount int32           `db:"breaking_count" json:"breaking_count"`
	WarningCount  int32           `db:"warning_count" json:"warning_count"`
	MinorCount    int32           `db:"minor_count" json:"minor_count"`
	Status        string          `db:"status" json:"status"`
	ScannedAt     time.Time       `db:"scanned_at" json:"scanned_at"`
}

type NotificationChannel struct {
	ID        uuid.UUID       `db:"id" json:"id"`
	TenantID  uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	Name      string          `db:"name" json:"name"`
	Type      string          `db:"type" json:"type"`
	Config    json.RawMessage `db:"config" json:"config"`
	IsActive  bool            `db:"is_active" json:"is_active"`
	CreatedAt time.Time       `db:"created_at" json:"created_at"`
}

type OrmStat struct {
	ID         uuid.UUID `db:"id" json:"id"`
	EnvID      uuid.UUID `db:"env_id" json:"env_id"`
	Model      string    `db:"model" json:"model"`
	Method     string    `db:"method" json:"method"`
	CallCount  int32     `db:"call_count" json:"call_count"`
	TotalMs    int32     `db:"total_ms" json:"total_ms"`
	AvgMs      *string   `db:"avg_ms" json:"avg_ms"`
	MaxMs      *int32    `db:"max_ms" json:"max_ms"`
	P95Ms      *int32    `db:"p95_ms" json:"p95_ms"`
	N1Detected bool      `db:"n1_detected" json:"n1_detected"`
	SampleSql  *string   `db:"sample_sql" json:"sample_sql"`
	Period     time.Time `db:"period" json:"period"`
	CreatedAt  time.Time `db:"created_at" json:"created_at"`
}

type PerfBudget struct {
	ID           uuid.UUID `db:"id" json:"id"`
	EnvID        uuid.UUID `db:"env_id" json:"env_id"`
	Module       string    `db:"module" json:"module"`
	Endpoint     string    `db:"endpoint" json:"endpoint"`
	ThresholdPct int32     `db:"threshold_pct" json:"threshold_pct"`
	IsActive     bool      `db:"is_active" json:"is_active"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

type PerfBudgetSample struct {
	ID          uuid.UUID        `db:"id" json:"id"`
	BudgetID    uuid.UUID        `db:"budget_id" json:"budget_id"`
	OverheadPct string           `db:"overhead_pct" json:"overhead_pct"`
	TotalMs     *int32           `db:"total_ms" json:"total_ms"`
	ModuleMs    *int32           `db:"module_ms" json:"module_ms"`
	Breakdown   *json.RawMessage `db:"breakdown" json:"breakdown"`
	SampledAt   time.Time        `db:"sampled_at" json:"sampled_at"`
}

type ProfilerRecording struct {
	ID           uuid.UUID        `db:"id" json:"id"`
	EnvID        uuid.UUID        `db:"env_id" json:"env_id"`
	TriggeredBy  *uuid.UUID       `db:"triggered_by" json:"triggered_by"`
	Name         string           `db:"name" json:"name"`
	Endpoint     *string          `db:"endpoint" json:"endpoint"`
	TotalMs      int32            `db:"total_ms" json:"total_ms"`
	SqlCount     *int32           `db:"sql_count" json:"sql_count"`
	SqlMs        *int32           `db:"sql_ms" json:"sql_ms"`
	PythonMs     *int32           `db:"python_ms" json:"python_ms"`
	Waterfall    json.RawMessage  `db:"waterfall" json:"waterfall"`
	ComputeChain *json.RawMessage `db:"compute_chain" json:"compute_chain"`
	N1Patterns   *json.RawMessage `db:"n1_patterns" json:"n1_patterns"`
	RawLogRef    *string          `db:"raw_log_ref" json:"raw_log_ref"`
	RecordedAt   time.Time        `db:"recorded_at" json:"recorded_at"`
}

type SchemaSnapshot struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	EnvID       uuid.UUID       `db:"env_id" json:"env_id"`
	CapturedAt  time.Time       `db:"captured_at" json:"captured_at"`
	Models      json.RawMessage `db:"models" json:"models"`
	AclRules    json.RawMessage `db:"acl_rules" json:"acl_rules"`
	RecordRules json.RawMessage `db:"record_rules" json:"record_rules"`
	ModelCount  *int32          `db:"model_count" json:"model_count"`
	FieldCount  *int32          `db:"field_count" json:"field_count"`
	DiffRef     *string         `db:"diff_ref" json:"diff_ref"`
}

type Session struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	UserID       uuid.UUID   `db:"user_id" json:"user_id"`
	TenantID     uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	RefreshToken string      `db:"refresh_token" json:"refresh_token"`
	UserAgent    *string     `db:"user_agent" json:"user_agent"`
	IpAddress    *netip.Addr `db:"ip_address" json:"ip_address"`
	ExpiresAt    time.Time   `db:"expires_at" json:"expires_at"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
	LastUsedAt   time.Time   `db:"last_used_at" json:"last_used_at"`
}

type Subscription struct {
	ID                   uuid.UUID  `db:"id" json:"id"`
	TenantID             uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	StripeCustomerID     *string    `db:"stripe_customer_id" json:"stripe_customer_id"`
	StripeSubscriptionID *string    `db:"stripe_subscription_id" json:"stripe_subscription_id"`
	StripePriceID        *string    `db:"stripe_price_id" json:"stripe_price_id"`
	Plan                 string     `db:"plan" json:"plan"`
	Status               string     `db:"status" json:"status"`
	CurrentPeriodStart   *time.Time `db:"current_period_start" json:"current_period_start"`
	CurrentPeriodEnd     *time.Time `db:"current_period_end" json:"current_period_end"`
	CancelAtPeriodEnd    bool       `db:"cancel_at_period_end" json:"cancel_at_period_end"`
	TrialEnd             *time.Time `db:"trial_end" json:"trial_end"`
	CreatedAt            time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time  `db:"updated_at" json:"updated_at"`
}

type Tenant struct {
	ID              uuid.UUID       `db:"id" json:"id"`
	Name            string          `db:"name" json:"name"`
	Slug            string          `db:"slug" json:"slug"`
	Plan            string          `db:"plan" json:"plan"`
	PlanStatus      string          `db:"plan_status" json:"plan_status"`
	TrialEndsAt     *time.Time      `db:"trial_ends_at" json:"trial_ends_at"`
	CreatedAt       time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time       `db:"updated_at" json:"updated_at"`
	Settings        json.RawMessage `db:"settings" json:"settings"`
	RetentionConfig json.RawMessage `db:"retention_config" json:"retention_config"`
}

type User struct {
	ID            uuid.UUID  `db:"id" json:"id"`
	TenantID      uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	Email         string     `db:"email" json:"email"`
	PasswordHash  string     `db:"password_hash" json:"password_hash"`
	FullName      *string    `db:"full_name" json:"full_name"`
	EmailVerified bool       `db:"email_verified" json:"email_verified"`
	IsActive      bool       `db:"is_active" json:"is_active"`
	LastLoginAt   *time.Time `db:"last_login_at" json:"last_login_at"`
	CreatedAt     time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time  `db:"updated_at" json:"updated_at"`
}
