// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: multi_tenant.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countUsersByTenant = `-- name: CountUsersByTenant :one
SELECT count(*) FROM users
WHERE tenant_id = $1
`

func (q *Queries) CountUsersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByTenant, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    name,
    slug,
    plan,
    plan_status,
    trial_ends_at,
    settings,
    retention_config
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, name, slug, plan, plan_status, trial_ends_at, created_at, updated_at, settings, retention_config
`

type CreateTenantParams struct {
	Name            string          `db:"name" json:"name"`
	Slug            string          `db:"slug" json:"slug"`
	Plan            string          `db:"plan" json:"plan"`
	PlanStatus      string          `db:"plan_status" json:"plan_status"`
	TrialEndsAt     *time.Time      `db:"trial_ends_at" json:"trial_ends_at"`
	Settings        json.RawMessage `db:"settings" json:"settings"`
	RetentionConfig json.RawMessage `db:"retention_config" json:"retention_config"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.Plan,
		arg.PlanStatus,
		arg.TrialEndsAt,
		arg.Settings,
		arg.RetentionConfig,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.PlanStatus,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.RetentionConfig,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    tenant_id,
    email,
    password_hash,
    full_name,
    role,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, email, password_hash, full_name, role, is_active, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	TenantID     uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Email        string    `db:"email" json:"email"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	FullName     *string   `db:"full_name" json:"full_name"`
	Role         string    `db:"role" json:"role"`
	IsActive     bool      `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Role,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET
    is_active = false,
    updated_at = now()
WHERE id = $1 AND tenant_id = $2
`

type DeactivateUserParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) error {
	_, err := q.db.Exec(ctx, deactivateUser, arg.ID, arg.TenantID)
	return err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants
WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1 AND tenant_id = $2
`

type DeleteUserParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.Exec(ctx, deleteUser, arg.ID, arg.TenantID)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, plan, plan_status, trial_ends_at, created_at, updated_at, settings, retention_config FROM tenants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.PlanStatus,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.RetentionConfig,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, plan, plan_status, trial_ends_at, created_at, updated_at, settings, retention_config FROM tenants
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.PlanStatus,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.RetentionConfig,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, password_hash, full_name, role, is_active, last_login_at, created_at, updated_at FROM users
WHERE email = $1 AND tenant_id = $2
LIMIT 1
`

type GetUserByEmailParams struct {
	Email    string    `db:"email" json:"email"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.Email, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailGlobal = `-- name: GetUserByEmailGlobal :one
SELECT u.id, u.tenant_id, u.email, u.password_hash, u.full_name, u.role, u.is_active, u.last_login_at, u.created_at, u.updated_at, t.slug AS tenant_slug, t.plan AS tenant_plan
FROM users u
JOIN tenants t ON u.tenant_id = t.id
WHERE u.email = $1 AND u.is_active = true
LIMIT 1
`

type GetUserByEmailGlobalRow struct {
	ID           uuid.UUID  `db:"id" json:"id"`
	TenantID     uuid.UUID  `db:"tenant_id" json:"tenant_id"`
	Email        string     `db:"email" json:"email"`
	PasswordHash string     `db:"password_hash" json:"password_hash"`
	FullName     *string    `db:"full_name" json:"full_name"`
	Role         string     `db:"role" json:"role"`
	IsActive     bool       `db:"is_active" json:"is_active"`
	LastLoginAt  *time.Time `db:"last_login_at" json:"last_login_at"`
	CreatedAt    time.Time  `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time  `db:"updated_at" json:"updated_at"`
	TenantSlug   string     `db:"tenant_slug" json:"tenant_slug"`
	TenantPlan   string     `db:"tenant_plan" json:"tenant_plan"`
}

// Login flow: user provides email only, we resolve tenant from the result
func (q *Queries) GetUserByEmailGlobal(ctx context.Context, email string) (GetUserByEmailGlobalRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailGlobal, email)
	var i GetUserByEmailGlobalRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantSlug,
		&i.TenantPlan,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, full_name, role, is_active, last_login_at, created_at, updated_at FROM users
WHERE id = $1 AND tenant_id = $2
LIMIT 1
`

type GetUserByIDParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, slug, plan, plan_status, trial_ends_at, created_at, updated_at, settings, retention_config FROM tenants
ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Plan,
			&i.PlanStatus,
			&i.TrialEndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Settings,
			&i.RetentionConfig,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT id, tenant_id, email, password_hash, full_name, role, is_active, last_login_at, created_at, updated_at FROM users
WHERE tenant_id = $1
ORDER BY created_at
`

func (q *Queries) ListUsersByTenant(ctx context.Context, tenantID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.FullName,
			&i.Role,
			&i.IsActive,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantPlan = `-- name: UpdateTenantPlan :one
UPDATE tenants
SET
    plan = $2,
    plan_status = $3,
    trial_ends_at = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, plan, plan_status, trial_ends_at, created_at, updated_at, settings, retention_config
`

type UpdateTenantPlanParams struct {
	ID          uuid.UUID  `db:"id" json:"id"`
	Plan        string     `db:"plan" json:"plan"`
	PlanStatus  string     `db:"plan_status" json:"plan_status"`
	TrialEndsAt *time.Time `db:"trial_ends_at" json:"trial_ends_at"`
}

func (q *Queries) UpdateTenantPlan(ctx context.Context, arg UpdateTenantPlanParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantPlan,
		arg.ID,
		arg.Plan,
		arg.PlanStatus,
		arg.TrialEndsAt,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.PlanStatus,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.RetentionConfig,
	)
	return i, err
}

const updateTenantRetention = `-- name: UpdateTenantRetention :one
UPDATE tenants
SET
    retention_config = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, plan, plan_status, trial_ends_at, created_at, updated_at, settings, retention_config
`

type UpdateTenantRetentionParams struct {
	ID              uuid.UUID       `db:"id" json:"id"`
	RetentionConfig json.RawMessage `db:"retention_config" json:"retention_config"`
}

func (q *Queries) UpdateTenantRetention(ctx context.Context, arg UpdateTenantRetentionParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantRetention, arg.ID, arg.RetentionConfig)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.PlanStatus,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.RetentionConfig,
	)
	return i, err
}

const updateTenantSettings = `-- name: UpdateTenantSettings :one
UPDATE tenants
SET
    name = $2,
    settings = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, name, slug, plan, plan_status, trial_ends_at, created_at, updated_at, settings, retention_config
`

type UpdateTenantSettingsParams struct {
	ID       uuid.UUID       `db:"id" json:"id"`
	Name     string          `db:"name" json:"name"`
	Settings json.RawMessage `db:"settings" json:"settings"`
}

func (q *Queries) UpdateTenantSettings(ctx context.Context, arg UpdateTenantSettingsParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantSettings, arg.ID, arg.Name, arg.Settings)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Plan,
		&i.PlanStatus,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Settings,
		&i.RetentionConfig,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    full_name = $2,
    role = $3,
    is_active = $4,
    updated_at = now()
WHERE id = $1 AND tenant_id = $5
RETURNING id, tenant_id, email, password_hash, full_name, role, is_active, last_login_at, created_at, updated_at
`

type UpdateUserParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	FullName *string   `db:"full_name" json:"full_name"`
	Role     string    `db:"role" json:"role"`
	IsActive bool      `db:"is_active" json:"is_active"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Role,
		arg.IsActive,
		arg.TenantID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Role,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET
    last_login_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET
    password_hash = $2,
    updated_at = now()
WHERE id = $1 AND tenant_id = $3
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	PasswordHash string    `db:"password_hash" json:"password_hash"`
	TenantID     uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash, arg.TenantID)
	return err
}
