// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: n1_detector.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const countN1Windows = `-- name: CountN1Windows :one
SELECT count(DISTINCT period)::int AS n1_windows
FROM orm_stats
WHERE env_id = $1
  AND n1_detected = true
  AND period >= $2
`

type CountN1WindowsParams struct {
	EnvID  uuid.UUID `db:"env_id" json:"env_id"`
	Period time.Time `db:"period" json:"period"`
}

// Counts distinct time windows that contain at least one N+1 detection.
func (q *Queries) CountN1Windows(ctx context.Context, arg CountN1WindowsParams) (int32, error) {
	row := q.db.QueryRow(ctx, countN1Windows, arg.EnvID, arg.Period)
	var n1_windows int32
	err := row.Scan(&n1_windows)
	return n1_windows, err
}

const getN1PatternsSummary = `-- name: GetN1PatternsSummary :many
SELECT
    model,
    method,
    count(*)::int               AS occurrences,
    sum(call_count)::int        AS total_calls,
    max(call_count)::int        AS peak_calls,
    sum(total_ms)::int          AS total_duration_ms,
    max(total_ms)::int          AS peak_ms,
    (sum(call_count)::float / GREATEST(count(*), 1))::float8 AS avg_calls_per_window,
    min(period)::timestamptz    AS first_seen,
    max(period)::timestamptz    AS last_seen,
    -- Pick the sample_sql from the row with the highest call_count.
    (array_agg(sample_sql ORDER BY call_count DESC))[1]::text AS sample_sql
FROM orm_stats
WHERE env_id = $1
  AND n1_detected = true
  AND period >= $2
GROUP BY model, method
ORDER BY total_duration_ms DESC
LIMIT $3
`

type GetN1PatternsSummaryParams struct {
	EnvID  uuid.UUID `db:"env_id" json:"env_id"`
	Period time.Time `db:"period" json:"period"`
	Limit  int32     `db:"limit" json:"limit"`
}

type GetN1PatternsSummaryRow struct {
	Model             string    `db:"model" json:"model"`
	Method            string    `db:"method" json:"method"`
	Occurrences       int32     `db:"occurrences" json:"occurrences"`
	TotalCalls        int32     `db:"total_calls" json:"total_calls"`
	PeakCalls         int32     `db:"peak_calls" json:"peak_calls"`
	TotalDurationMs   int32     `db:"total_duration_ms" json:"total_duration_ms"`
	PeakMs            int32     `db:"peak_ms" json:"peak_ms"`
	AvgCallsPerWindow float64   `db:"avg_calls_per_window" json:"avg_calls_per_window"`
	FirstSeen         time.Time `db:"first_seen" json:"first_seen"`
	LastSeen          time.Time `db:"last_seen" json:"last_seen"`
	SampleSql         string    `db:"sample_sql" json:"sample_sql"`
}

// Aggregates N+1 detections by model:method across time windows.
// Returns per-pattern stats including occurrence count, total/peak calls,
// total/peak duration, sample SQL, and first/last seen timestamps.
func (q *Queries) GetN1PatternsSummary(ctx context.Context, arg GetN1PatternsSummaryParams) ([]GetN1PatternsSummaryRow, error) {
	rows, err := q.db.Query(ctx, getN1PatternsSummary, arg.EnvID, arg.Period, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetN1PatternsSummaryRow{}
	for rows.Next() {
		var i GetN1PatternsSummaryRow
		if err := rows.Scan(
			&i.Model,
			&i.Method,
			&i.Occurrences,
			&i.TotalCalls,
			&i.PeakCalls,
			&i.TotalDurationMs,
			&i.PeakMs,
			&i.AvgCallsPerWindow,
			&i.FirstSeen,
			&i.LastSeen,
			&i.SampleSql,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getN1Timeline = `-- name: GetN1Timeline :many
SELECT
    period,
    count(*)::int           AS pattern_count,
    sum(call_count)::int    AS total_calls,
    sum(total_ms)::int      AS total_ms
FROM orm_stats
WHERE env_id = $1
  AND n1_detected = true
  AND period >= $2
GROUP BY period
ORDER BY period DESC
LIMIT $3
`

type GetN1TimelineParams struct {
	EnvID  uuid.UUID `db:"env_id" json:"env_id"`
	Period time.Time `db:"period" json:"period"`
	Limit  int32     `db:"limit" json:"limit"`
}

type GetN1TimelineRow struct {
	Period       time.Time `db:"period" json:"period"`
	PatternCount int32     `db:"pattern_count" json:"pattern_count"`
	TotalCalls   int32     `db:"total_calls" json:"total_calls"`
	TotalMs      int32     `db:"total_ms" json:"total_ms"`
}

// Returns per-period N+1 event counts for trend visualization.
func (q *Queries) GetN1Timeline(ctx context.Context, arg GetN1TimelineParams) ([]GetN1TimelineRow, error) {
	rows, err := q.db.Query(ctx, getN1Timeline, arg.EnvID, arg.Period, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetN1TimelineRow{}
	for rows.Next() {
		var i GetN1TimelineRow
		if err := rows.Scan(
			&i.Period,
			&i.PatternCount,
			&i.TotalCalls,
			&i.TotalMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listN1RecordingPatterns = `-- name: ListN1RecordingPatterns :many
SELECT
    pr.id,
    pr.name,
    pr.n1_patterns,
    pr.total_ms,
    pr.recorded_at
FROM profiler_recordings pr
WHERE pr.env_id = $1
  AND pr.n1_patterns IS NOT NULL
  AND pr.recorded_at >= $2
ORDER BY pr.recorded_at DESC
LIMIT $3
`

type ListN1RecordingPatternsParams struct {
	EnvID      uuid.UUID `db:"env_id" json:"env_id"`
	RecordedAt time.Time `db:"recorded_at" json:"recorded_at"`
	Limit      int32     `db:"limit" json:"limit"`
}

type ListN1RecordingPatternsRow struct {
	ID         uuid.UUID        `db:"id" json:"id"`
	Name       string           `db:"name" json:"name"`
	N1Patterns *json.RawMessage `db:"n1_patterns" json:"n1_patterns"`
	TotalMs    int32            `db:"total_ms" json:"total_ms"`
	RecordedAt time.Time        `db:"recorded_at" json:"recorded_at"`
}

// Extracts N+1 patterns from profiler recordings' n1_patterns JSONB.
func (q *Queries) ListN1RecordingPatterns(ctx context.Context, arg ListN1RecordingPatternsParams) ([]ListN1RecordingPatternsRow, error) {
	rows, err := q.db.Query(ctx, listN1RecordingPatterns, arg.EnvID, arg.RecordedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListN1RecordingPatternsRow{}
	for rows.Next() {
		var i ListN1RecordingPatternsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.N1Patterns,
			&i.TotalMs,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
