// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: orm_stats.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const deleteOldORMStats = `-- name: DeleteOldORMStats :execresult
DELETE FROM orm_stats
WHERE env_id IN (
    SELECT id FROM environments WHERE tenant_id = $1
)
AND period < $2
`

type DeleteOldORMStatsParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Period   time.Time `db:"period" json:"period"`
}

func (q *Queries) DeleteOldORMStats(ctx context.Context, arg DeleteOldORMStatsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldORMStats, arg.TenantID, arg.Period)
}

const getORMStatsAggregated = `-- name: GetORMStatsAggregated :many
SELECT
    model,
    method,
    sum(call_count)::int AS total_calls,
    sum(total_ms)::int AS total_duration_ms,
    max(max_ms) AS peak_ms,
    bool_or(n1_detected) AS has_n1
FROM orm_stats
WHERE env_id = $1
  AND period >= $2
GROUP BY model, method
ORDER BY total_duration_ms DESC
LIMIT $3
`

type GetORMStatsAggregatedParams struct {
	EnvID  uuid.UUID `db:"env_id" json:"env_id"`
	Period time.Time `db:"period" json:"period"`
	Limit  int32     `db:"limit" json:"limit"`
}

type GetORMStatsAggregatedRow struct {
	Model           string `db:"model" json:"model"`
	Method          string `db:"method" json:"method"`
	TotalCalls      int32  `db:"total_calls" json:"total_calls"`
	TotalDurationMs int32  `db:"total_duration_ms" json:"total_duration_ms"`
	PeakMs          any    `db:"peak_ms" json:"peak_ms"`
	HasN1           bool   `db:"has_n1" json:"has_n1"`
}

func (q *Queries) GetORMStatsAggregated(ctx context.Context, arg GetORMStatsAggregatedParams) ([]GetORMStatsAggregatedRow, error) {
	rows, err := q.db.Query(ctx, getORMStatsAggregated, arg.EnvID, arg.Period, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetORMStatsAggregatedRow{}
	for rows.Next() {
		var i GetORMStatsAggregatedRow
		if err := rows.Scan(
			&i.Model,
			&i.Method,
			&i.TotalCalls,
			&i.TotalDurationMs,
			&i.PeakMs,
			&i.HasN1,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertORMStat = `-- name: InsertORMStat :one
INSERT INTO orm_stats (
    env_id,
    model,
    method,
    call_count,
    total_ms,
    avg_ms,
    max_ms,
    p95_ms,
    n1_detected,
    sample_sql,
    period
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, env_id, model, method, call_count, total_ms, avg_ms, max_ms, p95_ms, n1_detected, sample_sql, period, created_at
`

type InsertORMStatParams struct {
	EnvID      uuid.UUID `db:"env_id" json:"env_id"`
	Model      string    `db:"model" json:"model"`
	Method     string    `db:"method" json:"method"`
	CallCount  int32     `db:"call_count" json:"call_count"`
	TotalMs    int32     `db:"total_ms" json:"total_ms"`
	AvgMs      *string   `db:"avg_ms" json:"avg_ms"`
	MaxMs      *int32    `db:"max_ms" json:"max_ms"`
	P95Ms      *int32    `db:"p95_ms" json:"p95_ms"`
	N1Detected bool      `db:"n1_detected" json:"n1_detected"`
	SampleSql  *string   `db:"sample_sql" json:"sample_sql"`
	Period     time.Time `db:"period" json:"period"`
}

func (q *Queries) InsertORMStat(ctx context.Context, arg InsertORMStatParams) (OrmStat, error) {
	row := q.db.QueryRow(ctx, insertORMStat,
		arg.EnvID,
		arg.Model,
		arg.Method,
		arg.CallCount,
		arg.TotalMs,
		arg.AvgMs,
		arg.MaxMs,
		arg.P95Ms,
		arg.N1Detected,
		arg.SampleSql,
		arg.Period,
	)
	var i OrmStat
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Model,
		&i.Method,
		&i.CallCount,
		&i.TotalMs,
		&i.AvgMs,
		&i.MaxMs,
		&i.P95Ms,
		&i.N1Detected,
		&i.SampleSql,
		&i.Period,
		&i.CreatedAt,
	)
	return i, err
}

const listN1Detections = `-- name: ListN1Detections :many
SELECT id, env_id, model, method, call_count, total_ms, avg_ms, max_ms, p95_ms, n1_detected, sample_sql, period, created_at FROM orm_stats
WHERE env_id = $1
  AND n1_detected = true
  AND period >= $2
ORDER BY call_count DESC
LIMIT $3
`

type ListN1DetectionsParams struct {
	EnvID  uuid.UUID `db:"env_id" json:"env_id"`
	Period time.Time `db:"period" json:"period"`
	Limit  int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListN1Detections(ctx context.Context, arg ListN1DetectionsParams) ([]OrmStat, error) {
	rows, err := q.db.Query(ctx, listN1Detections, arg.EnvID, arg.Period, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrmStat{}
	for rows.Next() {
		var i OrmStat
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Model,
			&i.Method,
			&i.CallCount,
			&i.TotalMs,
			&i.AvgMs,
			&i.MaxMs,
			&i.P95Ms,
			&i.N1Detected,
			&i.SampleSql,
			&i.Period,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listORMStatsByPeriod = `-- name: ListORMStatsByPeriod :many
SELECT id, env_id, model, method, call_count, total_ms, avg_ms, max_ms, p95_ms, n1_detected, sample_sql, period, created_at FROM orm_stats
WHERE env_id = $1
  AND period >= $2
  AND period <= $3
ORDER BY total_ms DESC
`

type ListORMStatsByPeriodParams struct {
	EnvID    uuid.UUID `db:"env_id" json:"env_id"`
	Period   time.Time `db:"period" json:"period"`
	Period_2 time.Time `db:"period_2" json:"period_2"`
}

func (q *Queries) ListORMStatsByPeriod(ctx context.Context, arg ListORMStatsByPeriodParams) ([]OrmStat, error) {
	rows, err := q.db.Query(ctx, listORMStatsByPeriod, arg.EnvID, arg.Period, arg.Period_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrmStat{}
	for rows.Next() {
		var i OrmStat
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Model,
			&i.Method,
			&i.CallCount,
			&i.TotalMs,
			&i.AvgMs,
			&i.MaxMs,
			&i.P95Ms,
			&i.N1Detected,
			&i.SampleSql,
			&i.Period,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopORMStats = `-- name: ListTopORMStats :many
SELECT id, env_id, model, method, call_count, total_ms, avg_ms, max_ms, p95_ms, n1_detected, sample_sql, period, created_at FROM orm_stats
WHERE env_id = $1
  AND period >= $2
ORDER BY total_ms DESC
LIMIT $3
`

type ListTopORMStatsParams struct {
	EnvID  uuid.UUID `db:"env_id" json:"env_id"`
	Period time.Time `db:"period" json:"period"`
	Limit  int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListTopORMStats(ctx context.Context, arg ListTopORMStatsParams) ([]OrmStat, error) {
	rows, err := q.db.Query(ctx, listTopORMStats, arg.EnvID, arg.Period, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrmStat{}
	for rows.Next() {
		var i OrmStat
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Model,
			&i.Method,
			&i.CallCount,
			&i.TotalMs,
			&i.AvgMs,
			&i.MaxMs,
			&i.P95Ms,
			&i.N1Detected,
			&i.SampleSql,
			&i.Period,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
