// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: perf_budges.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const createPerfBudget = `-- name: CreatePerfBudget :one
INSERT INTO perf_budgets (
    env_id,
    module,
    endpoint,
    threshold_pct
) VALUES (
    $1, $2, $3, $4
) RETURNING id, env_id, module, endpoint, threshold_pct, is_active, created_at
`

type CreatePerfBudgetParams struct {
	EnvID        uuid.UUID `db:"env_id" json:"env_id"`
	Module       string    `db:"module" json:"module"`
	Endpoint     string    `db:"endpoint" json:"endpoint"`
	ThresholdPct int32     `db:"threshold_pct" json:"threshold_pct"`
}

func (q *Queries) CreatePerfBudget(ctx context.Context, arg CreatePerfBudgetParams) (PerfBudget, error) {
	row := q.db.QueryRow(ctx, createPerfBudget,
		arg.EnvID,
		arg.Module,
		arg.Endpoint,
		arg.ThresholdPct,
	)
	var i PerfBudget
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Module,
		&i.Endpoint,
		&i.ThresholdPct,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOldBudgetSamples = `-- name: DeleteOldBudgetSamples :execresult
DELETE FROM perf_budget_samples
WHERE budget_id IN (
    SELECT pb.id FROM perf_budgets pb
    JOIN environments e ON pb.env_id = e.id
    WHERE e.tenant_id = $1
)
AND sampled_at < $2
`

type DeleteOldBudgetSamplesParams struct {
	TenantID  uuid.UUID `db:"tenant_id" json:"tenant_id"`
	SampledAt time.Time `db:"sampled_at" json:"sampled_at"`
}

func (q *Queries) DeleteOldBudgetSamples(ctx context.Context, arg DeleteOldBudgetSamplesParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldBudgetSamples, arg.TenantID, arg.SampledAt)
}

const deletePerfBudget = `-- name: DeletePerfBudget :exec
DELETE FROM perf_budgets
WHERE id = $1 AND env_id = $2
`

type DeletePerfBudgetParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
}

func (q *Queries) DeletePerfBudget(ctx context.Context, arg DeletePerfBudgetParams) error {
	_, err := q.db.Exec(ctx, deletePerfBudget, arg.ID, arg.EnvID)
	return err
}

const getBudgetAverage7d = `-- name: GetBudgetAverage7d :one
SELECT
    CASE WHEN count(overhead_pct) > 0 THEN avg(overhead_pct)::numeric(5,2) ELSE 0.00 END AS avg_overhead,
    CASE WHEN count(overhead_pct) > 0 THEN max(overhead_pct) ELSE 0 END AS max_overhead,
    count(overhead_pct) AS sample_count
FROM perf_budget_samples
WHERE budget_id = $1
  AND sampled_at > now() - interval '7 days'
`

type GetBudgetAverage7dRow struct {
	AvgOverhead float64 `db:"avg_overhead" json:"avg_overhead"`
	MaxOverhead int32   `db:"max_overhead" json:"max_overhead"`
	SampleCount int64   `db:"sample_count" json:"sample_count"`
}

func (q *Queries) GetBudgetAverage7d(ctx context.Context, budgetID uuid.UUID) (GetBudgetAverage7dRow, error) {
	row := q.db.QueryRow(ctx, getBudgetAverage7d, budgetID)
	var i GetBudgetAverage7dRow
	err := row.Scan(&i.AvgOverhead, &i.MaxOverhead, &i.SampleCount)
	return i, err
}

const getLatestBudgetSample = `-- name: GetLatestBudgetSample :one
SELECT id, budget_id, overhead_pct, total_ms, module_ms, breakdown, sampled_at FROM perf_budget_samples
WHERE budget_id = $1
ORDER BY sampled_at DESC
LIMIT 1
`

func (q *Queries) GetLatestBudgetSample(ctx context.Context, budgetID uuid.UUID) (PerfBudgetSample, error) {
	row := q.db.QueryRow(ctx, getLatestBudgetSample, budgetID)
	var i PerfBudgetSample
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.OverheadPct,
		&i.TotalMs,
		&i.ModuleMs,
		&i.Breakdown,
		&i.SampledAt,
	)
	return i, err
}

const getPerfBudget = `-- name: GetPerfBudget :one
SELECT id, env_id, module, endpoint, threshold_pct, is_active, created_at FROM perf_budgets
WHERE id = $1 AND env_id = $2
LIMIT 1
`

type GetPerfBudgetParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
}

func (q *Queries) GetPerfBudget(ctx context.Context, arg GetPerfBudgetParams) (PerfBudget, error) {
	row := q.db.QueryRow(ctx, getPerfBudget, arg.ID, arg.EnvID)
	var i PerfBudget
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Module,
		&i.Endpoint,
		&i.ThresholdPct,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const insertBudgetSample = `-- name: InsertBudgetSample :one

INSERT INTO perf_budget_samples (
    budget_id,
    overhead_pct,
    total_ms,
    module_ms,
    breakdown
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, budget_id, overhead_pct, total_ms, module_ms, breakdown, sampled_at
`

type InsertBudgetSampleParams struct {
	BudgetID    uuid.UUID        `db:"budget_id" json:"budget_id"`
	OverheadPct string           `db:"overhead_pct" json:"overhead_pct"`
	TotalMs     *int32           `db:"total_ms" json:"total_ms"`
	ModuleMs    *int32           `db:"module_ms" json:"module_ms"`
	Breakdown   *json.RawMessage `db:"breakdown" json:"breakdown"`
}

// ════════════════════════════════════════════
//
//	Budget Samples (from ingest worker)
//
// ════════════════════════════════════════════
func (q *Queries) InsertBudgetSample(ctx context.Context, arg InsertBudgetSampleParams) (PerfBudgetSample, error) {
	row := q.db.QueryRow(ctx, insertBudgetSample,
		arg.BudgetID,
		arg.OverheadPct,
		arg.TotalMs,
		arg.ModuleMs,
		arg.Breakdown,
	)
	var i PerfBudgetSample
	err := row.Scan(
		&i.ID,
		&i.BudgetID,
		&i.OverheadPct,
		&i.TotalMs,
		&i.ModuleMs,
		&i.Breakdown,
		&i.SampledAt,
	)
	return i, err
}

const listAllPerfBudgetsByEnv = `-- name: ListAllPerfBudgetsByEnv :many
SELECT id, env_id, module, endpoint, threshold_pct, is_active, created_at FROM perf_budgets
WHERE env_id = $1
ORDER BY module, endpoint
`

func (q *Queries) ListAllPerfBudgetsByEnv(ctx context.Context, envID uuid.UUID) ([]PerfBudget, error) {
	rows, err := q.db.Query(ctx, listAllPerfBudgetsByEnv, envID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerfBudget{}
	for rows.Next() {
		var i PerfBudget
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Module,
			&i.Endpoint,
			&i.ThresholdPct,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetSamples = `-- name: ListBudgetSamples :many
SELECT id, budget_id, overhead_pct, total_ms, module_ms, breakdown, sampled_at FROM perf_budget_samples
WHERE budget_id = $1
ORDER BY sampled_at DESC
LIMIT $2
`

type ListBudgetSamplesParams struct {
	BudgetID uuid.UUID `db:"budget_id" json:"budget_id"`
	Limit    int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListBudgetSamples(ctx context.Context, arg ListBudgetSamplesParams) ([]PerfBudgetSample, error) {
	rows, err := q.db.Query(ctx, listBudgetSamples, arg.BudgetID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerfBudgetSample{}
	for rows.Next() {
		var i PerfBudgetSample
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.OverheadPct,
			&i.TotalMs,
			&i.ModuleMs,
			&i.Breakdown,
			&i.SampledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgetSamplesBetween = `-- name: ListBudgetSamplesBetween :many
SELECT id, budget_id, overhead_pct, total_ms, module_ms, breakdown, sampled_at FROM perf_budget_samples
WHERE budget_id = $1
  AND sampled_at >= $2
  AND sampled_at <= $3
ORDER BY sampled_at ASC
`

type ListBudgetSamplesBetweenParams struct {
	BudgetID    uuid.UUID `db:"budget_id" json:"budget_id"`
	SampledAt   time.Time `db:"sampled_at" json:"sampled_at"`
	SampledAt_2 time.Time `db:"sampled_at_2" json:"sampled_at_2"`
}

func (q *Queries) ListBudgetSamplesBetween(ctx context.Context, arg ListBudgetSamplesBetweenParams) ([]PerfBudgetSample, error) {
	rows, err := q.db.Query(ctx, listBudgetSamplesBetween, arg.BudgetID, arg.SampledAt, arg.SampledAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerfBudgetSample{}
	for rows.Next() {
		var i PerfBudgetSample
		if err := rows.Scan(
			&i.ID,
			&i.BudgetID,
			&i.OverheadPct,
			&i.TotalMs,
			&i.ModuleMs,
			&i.Breakdown,
			&i.SampledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPerfBudgets = `-- name: ListPerfBudgets :many
SELECT id, env_id, module, endpoint, threshold_pct, is_active, created_at FROM perf_budgets
WHERE env_id = $1 AND is_active = true
ORDER BY module, endpoint
`

func (q *Queries) ListPerfBudgets(ctx context.Context, envID uuid.UUID) ([]PerfBudget, error) {
	rows, err := q.db.Query(ctx, listPerfBudgets, envID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PerfBudget{}
	for rows.Next() {
		var i PerfBudget
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.Module,
			&i.Endpoint,
			&i.ThresholdPct,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePerfBudget = `-- name: UpdatePerfBudget :one
UPDATE perf_budgets
SET
    threshold_pct = $2,
    is_active = $3
WHERE id = $1 AND env_id = $4
RETURNING id, env_id, module, endpoint, threshold_pct, is_active, created_at
`

type UpdatePerfBudgetParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	ThresholdPct int32     `db:"threshold_pct" json:"threshold_pct"`
	IsActive     bool      `db:"is_active" json:"is_active"`
	EnvID        uuid.UUID `db:"env_id" json:"env_id"`
}

func (q *Queries) UpdatePerfBudget(ctx context.Context, arg UpdatePerfBudgetParams) (PerfBudget, error) {
	row := q.db.QueryRow(ctx, updatePerfBudget,
		arg.ID,
		arg.ThresholdPct,
		arg.IsActive,
		arg.EnvID,
	)
	var i PerfBudget
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.Module,
		&i.Endpoint,
		&i.ThresholdPct,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
