// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: profilier.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const countRecordingsByEnv = `-- name: CountRecordingsByEnv :one
SELECT count(*) FROM profiler_recordings
WHERE env_id = $1
`

func (q *Queries) CountRecordingsByEnv(ctx context.Context, envID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecordingsByEnv, envID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProfilerRecording = `-- name: CreateProfilerRecording :one
INSERT INTO profiler_recordings (
    env_id,
    triggered_by,
    name,
    endpoint,
    total_ms,
    sql_count,
    sql_ms,
    python_ms,
    waterfall,
    compute_chain,
    n1_patterns,
    raw_log_ref
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, env_id, triggered_by, name, endpoint, total_ms, sql_count, sql_ms, python_ms, waterfall, compute_chain, n1_patterns, raw_log_ref, recorded_at
`

type CreateProfilerRecordingParams struct {
	EnvID        uuid.UUID        `db:"env_id" json:"env_id"`
	TriggeredBy  *uuid.UUID       `db:"triggered_by" json:"triggered_by"`
	Name         string           `db:"name" json:"name"`
	Endpoint     *string          `db:"endpoint" json:"endpoint"`
	TotalMs      int32            `db:"total_ms" json:"total_ms"`
	SqlCount     *int32           `db:"sql_count" json:"sql_count"`
	SqlMs        *int32           `db:"sql_ms" json:"sql_ms"`
	PythonMs     *int32           `db:"python_ms" json:"python_ms"`
	Waterfall    json.RawMessage  `db:"waterfall" json:"waterfall"`
	ComputeChain *json.RawMessage `db:"compute_chain" json:"compute_chain"`
	N1Patterns   *json.RawMessage `db:"n1_patterns" json:"n1_patterns"`
	RawLogRef    *string          `db:"raw_log_ref" json:"raw_log_ref"`
}

func (q *Queries) CreateProfilerRecording(ctx context.Context, arg CreateProfilerRecordingParams) (ProfilerRecording, error) {
	row := q.db.QueryRow(ctx, createProfilerRecording,
		arg.EnvID,
		arg.TriggeredBy,
		arg.Name,
		arg.Endpoint,
		arg.TotalMs,
		arg.SqlCount,
		arg.SqlMs,
		arg.PythonMs,
		arg.Waterfall,
		arg.ComputeChain,
		arg.N1Patterns,
		arg.RawLogRef,
	)
	var i ProfilerRecording
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.TriggeredBy,
		&i.Name,
		&i.Endpoint,
		&i.TotalMs,
		&i.SqlCount,
		&i.SqlMs,
		&i.PythonMs,
		&i.Waterfall,
		&i.ComputeChain,
		&i.N1Patterns,
		&i.RawLogRef,
		&i.RecordedAt,
	)
	return i, err
}

const deleteOldProfilerRecordings = `-- name: DeleteOldProfilerRecordings :execresult
DELETE FROM profiler_recordings
WHERE env_id IN (
    SELECT id FROM environments WHERE tenant_id = $1
)
AND recorded_at < $2
`

type DeleteOldProfilerRecordingsParams struct {
	TenantID   uuid.UUID `db:"tenant_id" json:"tenant_id"`
	RecordedAt time.Time `db:"recorded_at" json:"recorded_at"`
}

func (q *Queries) DeleteOldProfilerRecordings(ctx context.Context, arg DeleteOldProfilerRecordingsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldProfilerRecordings, arg.TenantID, arg.RecordedAt)
}

const getProfilerRecording = `-- name: GetProfilerRecording :one
SELECT id, env_id, triggered_by, name, endpoint, total_ms, sql_count, sql_ms, python_ms, waterfall, compute_chain, n1_patterns, raw_log_ref, recorded_at FROM profiler_recordings
WHERE id = $1 AND env_id = $2
LIMIT 1
`

type GetProfilerRecordingParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
}

func (q *Queries) GetProfilerRecording(ctx context.Context, arg GetProfilerRecordingParams) (ProfilerRecording, error) {
	row := q.db.QueryRow(ctx, getProfilerRecording, arg.ID, arg.EnvID)
	var i ProfilerRecording
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.TriggeredBy,
		&i.Name,
		&i.Endpoint,
		&i.TotalMs,
		&i.SqlCount,
		&i.SqlMs,
		&i.PythonMs,
		&i.Waterfall,
		&i.ComputeChain,
		&i.N1Patterns,
		&i.RawLogRef,
		&i.RecordedAt,
	)
	return i, err
}

const listProfilerRecordings = `-- name: ListProfilerRecordings :many
SELECT id, env_id, triggered_by, name, endpoint,
       total_ms, sql_count, sql_ms, python_ms,
       n1_patterns IS NOT NULL AS has_n1,
       raw_log_ref, recorded_at
FROM profiler_recordings
WHERE env_id = $1
ORDER BY recorded_at DESC
LIMIT $2 OFFSET $3
`

type ListProfilerRecordingsParams struct {
	EnvID  uuid.UUID `db:"env_id" json:"env_id"`
	Limit  int32     `db:"limit" json:"limit"`
	Offset int32     `db:"offset" json:"offset"`
}

type ListProfilerRecordingsRow struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	EnvID       uuid.UUID   `db:"env_id" json:"env_id"`
	TriggeredBy *uuid.UUID  `db:"triggered_by" json:"triggered_by"`
	Name        string      `db:"name" json:"name"`
	Endpoint    *string     `db:"endpoint" json:"endpoint"`
	TotalMs     int32       `db:"total_ms" json:"total_ms"`
	SqlCount    *int32      `db:"sql_count" json:"sql_count"`
	SqlMs       *int32      `db:"sql_ms" json:"sql_ms"`
	PythonMs    *int32      `db:"python_ms" json:"python_ms"`
	HasN1       interface{} `db:"has_n1" json:"has_n1"`
	RawLogRef   *string     `db:"raw_log_ref" json:"raw_log_ref"`
	RecordedAt  time.Time   `db:"recorded_at" json:"recorded_at"`
}

func (q *Queries) ListProfilerRecordings(ctx context.Context, arg ListProfilerRecordingsParams) ([]ListProfilerRecordingsRow, error) {
	rows, err := q.db.Query(ctx, listProfilerRecordings, arg.EnvID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfilerRecordingsRow{}
	for rows.Next() {
		var i ListProfilerRecordingsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.TriggeredBy,
			&i.Name,
			&i.Endpoint,
			&i.TotalMs,
			&i.SqlCount,
			&i.SqlMs,
			&i.PythonMs,
			&i.HasN1,
			&i.RawLogRef,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSlowRecordings = `-- name: ListSlowRecordings :many
SELECT id, env_id, triggered_by, name, endpoint, total_ms, sql_count, sql_ms, python_ms, waterfall, compute_chain, n1_patterns, raw_log_ref, recorded_at FROM profiler_recordings
WHERE env_id = $1 AND total_ms > $2
ORDER BY total_ms DESC
LIMIT $3
`

type ListSlowRecordingsParams struct {
	EnvID   uuid.UUID `db:"env_id" json:"env_id"`
	TotalMs int32     `db:"total_ms" json:"total_ms"`
	Limit   int32     `db:"limit" json:"limit"`
}

func (q *Queries) ListSlowRecordings(ctx context.Context, arg ListSlowRecordingsParams) ([]ProfilerRecording, error) {
	rows, err := q.db.Query(ctx, listSlowRecordings, arg.EnvID, arg.TotalMs, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProfilerRecording{}
	for rows.Next() {
		var i ProfilerRecording
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.TriggeredBy,
			&i.Name,
			&i.Endpoint,
			&i.TotalMs,
			&i.SqlCount,
			&i.SqlMs,
			&i.PythonMs,
			&i.Waterfall,
			&i.ComputeChain,
			&i.N1Patterns,
			&i.RawLogRef,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
