// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcknowledgeAlert(ctx context.Context, arg AcknowledgeAlertParams) (Alert, error)
	AcknowledgeAllAlerts(ctx context.Context, arg AcknowledgeAllAlertsParams) (pgconn.CommandTag, error)
	AcknowledgeErrorGroup(ctx context.Context, arg AcknowledgeErrorGroupParams) (ErrorGroup, error)
	// Merge new user IDs into the existing array (deduplicated)
	AppendAffectedUsers(ctx context.Context, arg AppendAffectedUsersParams) error
	CheckEnvironmentNameExists(ctx context.Context, arg CheckEnvironmentNameExistsParams) (bool, error)
	CountAuditLogs(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountEnvironmentsByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CountEnvironmentsByTenantAndStatus(ctx context.Context, arg CountEnvironmentsByTenantAndStatusParams) (int64, error)
	CountEnvironmentsByTenantAndType(ctx context.Context, arg CountEnvironmentsByTenantAndTypeParams) (int64, error)
	CountEnvironmentsByTenantTypeAndStatus(ctx context.Context, arg CountEnvironmentsByTenantTypeAndStatusParams) (int64, error)
	CountErrorGroupsByEnv(ctx context.Context, envID uuid.UUID) (int64, error)
	CountErrorGroupsByStatus(ctx context.Context, arg CountErrorGroupsByStatusParams) (int64, error)
	CountRecordingsByEnv(ctx context.Context, envID uuid.UUID) (int64, error)
	CountSchemasByEnv(ctx context.Context, envID uuid.UUID) (int64, error)
	CountUnacknowledgedAlerts(ctx context.Context, envID uuid.UUID) (int64, error)
	CountUsersByTenant(ctx context.Context, tenantID uuid.UUID) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	// ════════════════════════════════════════════
	//  Alerts
	// ════════════════════════════════════════════
	CreateAlert(ctx context.Context, arg CreateAlertParams) (Alert, error)
	// ════════════════════════════════════════════
	//  Alert Deliveries (used by notification worker)
	// ════════════════════════════════════════════
	CreateAlertDelivery(ctx context.Context, arg CreateAlertDeliveryParams) (AlertDelivery, error)
	CreateAnonProfile(ctx context.Context, arg CreateAnonProfileParams) (AnonProfile, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateBillingEvent(ctx context.Context, arg CreateBillingEventParams) (BillingEvent, error)
	CreateEnvironment(ctx context.Context, arg CreateEnvironmentParams) (Environment, error)
	CreateMigrationScan(ctx context.Context, arg CreateMigrationScanParams) (MigrationScan, error)
	// ════════════════════════════════════════════
	//  Notification Channels
	// ════════════════════════════════════════════
	CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error)
	CreatePerfBudget(ctx context.Context, arg CreatePerfBudgetParams) (PerfBudget, error)
	CreateProfilerRecording(ctx context.Context, arg CreateProfilerRecordingParams) (ProfilerRecording, error)
	CreateSchemaSnapshot(ctx context.Context, arg CreateSchemaSnapshotParams) (SchemaSnapshot, error)
	// ════════════════════════════════════════════
	//  Sessions
	// ════════════════════════════════════════════
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeactivateUser(ctx context.Context, arg DeactivateUserParams) error
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error
	DeleteAnonProfile(ctx context.Context, arg DeleteAnonProfileParams) error
	DeleteEnvironment(ctx context.Context, arg DeleteEnvironmentParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context) (pgconn.CommandTag, error)
	DeleteMigrationScan(ctx context.Context, arg DeleteMigrationScanParams) error
	DeleteNotificationChannel(ctx context.Context, arg DeleteNotificationChannelParams) error
	DeleteOldAlerts(ctx context.Context, arg DeleteOldAlertsParams) (pgconn.CommandTag, error)
	DeleteOldAuditLogs(ctx context.Context, arg DeleteOldAuditLogsParams) (pgconn.CommandTag, error)
	DeleteOldBudgetSamples(ctx context.Context, arg DeleteOldBudgetSamplesParams) (pgconn.CommandTag, error)
	DeleteOldErrorGroups(ctx context.Context, arg DeleteOldErrorGroupsParams) (pgconn.CommandTag, error)
	DeleteOldHeartbeats(ctx context.Context, arg DeleteOldHeartbeatsParams) (pgconn.CommandTag, error)
	DeleteOldORMStats(ctx context.Context, arg DeleteOldORMStatsParams) (pgconn.CommandTag, error)
	DeleteOldProfilerRecordings(ctx context.Context, arg DeleteOldProfilerRecordingsParams) (pgconn.CommandTag, error)
	// Keep the N most recent per env, delete the rest for a tenant
	// Call from retention worker with the keep count
	DeleteOldSchemaSnapshots(ctx context.Context, arg DeleteOldSchemaSnapshotsParams) (pgconn.CommandTag, error)
	DeletePerfBudget(ctx context.Context, arg DeletePerfBudgetParams) error
	DeleteSubscription(ctx context.Context, tenantID uuid.UUID) error
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	DisconnectAgent(ctx context.Context, agentID *string) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, arg GetAPIKeyByIDParams) (ApiKey, error)
	GetAlert(ctx context.Context, id uuid.UUID) (Alert, error)
	GetAlertByID(ctx context.Context, arg GetAlertByIDParams) (Alert, error)
	GetAnonProfile(ctx context.Context, arg GetAnonProfileParams) (AnonProfile, error)
	GetAnonProfileByID(ctx context.Context, id uuid.UUID) (AnonProfile, error)
	// Used in tests and admin views — filter by tenant + action without pagination
	GetAuditLogsByTenant(ctx context.Context, arg GetAuditLogsByTenantParams) ([]AuditLog, error)
	GetBillingEventByStripeID(ctx context.Context, stripeEventID string) (BillingEvent, error)
	GetBudgetAverage7d(ctx context.Context, budgetID uuid.UUID) (GetBudgetAverage7dRow, error)
	GetEnvironmentByAgentID(ctx context.Context, agentID *string) (Environment, error)
	GetEnvironmentByID(ctx context.Context, arg GetEnvironmentByIDParams) (Environment, error)
	GetErrorGroupByID(ctx context.Context, arg GetErrorGroupByIDParams) (ErrorGroup, error)
	GetErrorGroupBySignature(ctx context.Context, arg GetErrorGroupBySignatureParams) (ErrorGroup, error)
	GetFeatureFlags(ctx context.Context, id uuid.UUID) (json.RawMessage, error)
	GetLatestBudgetSample(ctx context.Context, budgetID uuid.UUID) (PerfBudgetSample, error)
	GetLatestHeartbeat(ctx context.Context, envID uuid.UUID) (AgentHeartbeat, error)
	GetLatestMigrationScan(ctx context.Context, envID uuid.UUID) (MigrationScan, error)
	GetLatestSchema(ctx context.Context, envID uuid.UUID) (SchemaSnapshot, error)
	GetMigrationScan(ctx context.Context, arg GetMigrationScanParams) (MigrationScan, error)
	GetNotificationChannel(ctx context.Context, arg GetNotificationChannelParams) (NotificationChannel, error)
	GetORMStatsAggregated(ctx context.Context, arg GetORMStatsAggregatedParams) ([]GetORMStatsAggregatedRow, error)
	GetPerfBudget(ctx context.Context, arg GetPerfBudgetParams) (PerfBudget, error)
	GetProfilerRecording(ctx context.Context, arg GetProfilerRecordingParams) (ProfilerRecording, error)
	GetSchemaByID(ctx context.Context, arg GetSchemaByIDParams) (SchemaSnapshot, error)
	GetSchemaSnapshotByID(ctx context.Context, id uuid.UUID) (SchemaSnapshot, error)
	GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error)
	GetSessionByToken(ctx context.Context, refreshToken string) (GetSessionByTokenRow, error)
	GetSubscriptionByStripeCustomer(ctx context.Context, stripeCustomerID *string) (Subscription, error)
	GetSubscriptionByStripeID(ctx context.Context, stripeSubscriptionID *string) (Subscription, error)
	GetSubscriptionByTenant(ctx context.Context, tenantID uuid.UUID) (Subscription, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetTwoSchemasForDiff(ctx context.Context, dollar_1 []uuid.UUID) ([]SchemaSnapshot, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error)
	// Login flow: user provides email only, we resolve tenant from the result
	GetUserByEmailGlobal(ctx context.Context, email string) (GetUserByEmailGlobalRow, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (User, error)
	// Fetch user by id across tenants (used by password reset flows)
	GetUserByIDGlobal(ctx context.Context, id uuid.UUID) (GetUserByIDGlobalRow, error)
	// ════════════════════════════════════════════
	//  Budget Samples (from ingest worker)
	// ════════════════════════════════════════════
	InsertBudgetSample(ctx context.Context, arg InsertBudgetSampleParams) (PerfBudgetSample, error)
	// ════════════════════════════════════════════
	//  Agent Heartbeats
	// ════════════════════════════════════════════
	InsertHeartbeat(ctx context.Context, arg InsertHeartbeatParams) (AgentHeartbeat, error)
	InsertORMStat(ctx context.Context, arg InsertORMStatParams) (OrmStat, error)
	ListAPIKeysByTenant(ctx context.Context, tenantID uuid.UUID) ([]ListAPIKeysByTenantRow, error)
	ListActiveNotificationChannels(ctx context.Context, tenantID uuid.UUID) ([]NotificationChannel, error)
	ListAlertDeliveries(ctx context.Context, alertID uuid.UUID) ([]AlertDelivery, error)
	ListAlerts(ctx context.Context, arg ListAlertsParams) ([]Alert, error)
	ListAlertsByType(ctx context.Context, arg ListAlertsByTypeParams) ([]Alert, error)
	ListAllPerfBudgetsByEnv(ctx context.Context, envID uuid.UUID) ([]PerfBudget, error)
	ListAnonProfiles(ctx context.Context, tenantID uuid.UUID) ([]AnonProfile, error)
	ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error)
	ListAuditLogsBetween(ctx context.Context, arg ListAuditLogsBetweenParams) ([]AuditLog, error)
	ListAuditLogsByAction(ctx context.Context, arg ListAuditLogsByActionParams) ([]AuditLog, error)
	ListAuditLogsByResource(ctx context.Context, arg ListAuditLogsByResourceParams) ([]AuditLog, error)
	ListAuditLogsByUser(ctx context.Context, arg ListAuditLogsByUserParams) ([]AuditLog, error)
	ListBudgetSamples(ctx context.Context, arg ListBudgetSamplesParams) ([]PerfBudgetSample, error)
	ListBudgetSamplesBetween(ctx context.Context, arg ListBudgetSamplesBetweenParams) ([]PerfBudgetSample, error)
	ListEnvironmentsByTenant(ctx context.Context, tenantID uuid.UUID) ([]Environment, error)
	ListEnvironmentsByTenantAndStatus(ctx context.Context, arg ListEnvironmentsByTenantAndStatusParams) ([]Environment, error)
	ListEnvironmentsByTenantAndType(ctx context.Context, arg ListEnvironmentsByTenantAndTypeParams) ([]Environment, error)
	ListEnvironmentsByTenantTypeAndStatus(ctx context.Context, arg ListEnvironmentsByTenantTypeAndStatusParams) ([]Environment, error)
	ListErrorGroups(ctx context.Context, arg ListErrorGroupsParams) ([]ErrorGroup, error)
	ListErrorGroupsByStatus(ctx context.Context, arg ListErrorGroupsByStatusParams) ([]ErrorGroup, error)
	ListErrorGroupsByType(ctx context.Context, arg ListErrorGroupsByTypeParams) ([]ErrorGroup, error)
	ListHeartbeats(ctx context.Context, arg ListHeartbeatsParams) ([]AgentHeartbeat, error)
	ListMigrationScans(ctx context.Context, arg ListMigrationScansParams) ([]MigrationScan, error)
	ListN1Detections(ctx context.Context, arg ListN1DetectionsParams) ([]OrmStat, error)
	ListNotificationChannels(ctx context.Context, tenantID uuid.UUID) ([]NotificationChannel, error)
	ListORMStatsByPeriod(ctx context.Context, arg ListORMStatsByPeriodParams) ([]OrmStat, error)
	ListPendingDeliveries(ctx context.Context, limit int32) ([]ListPendingDeliveriesRow, error)
	ListPerfBudgets(ctx context.Context, envID uuid.UUID) ([]PerfBudget, error)
	ListProfilerRecordings(ctx context.Context, arg ListProfilerRecordingsParams) ([]ListProfilerRecordingsRow, error)
	ListSchemaSnapshots(ctx context.Context, arg ListSchemaSnapshotsParams) ([]ListSchemaSnapshotsRow, error)
	ListSessions(ctx context.Context, userID uuid.UUID) ([]Session, error)
	ListSlowRecordings(ctx context.Context, arg ListSlowRecordingsParams) ([]ProfilerRecording, error)
	ListStaleAgents(ctx context.Context, dollar_1 pgtype.Interval) ([]ListStaleAgentsRow, error)
	ListTenants(ctx context.Context) ([]Tenant, error)
	ListTopORMStats(ctx context.Context, arg ListTopORMStatsParams) ([]OrmStat, error)
	ListUnacknowledgedAlerts(ctx context.Context, arg ListUnacknowledgedAlertsParams) ([]Alert, error)
	ListUnprocessedBillingEvents(ctx context.Context, limit int32) ([]BillingEvent, error)
	ListUsersByTenant(ctx context.Context, tenantID uuid.UUID) ([]User, error)
	MarkBillingEventFailed(ctx context.Context, arg MarkBillingEventFailedParams) error
	MarkBillingEventProcessed(ctx context.Context, id uuid.UUID) error
	MarkDeliveryFailed(ctx context.Context, arg MarkDeliveryFailedParams) error
	MarkDeliverySent(ctx context.Context, id uuid.UUID) error
	RegisterAgent(ctx context.Context, arg RegisterAgentParams) (Environment, error)
	ReopenErrorGroup(ctx context.Context, arg ReopenErrorGroupParams) (ErrorGroup, error)
	ResolveErrorGroup(ctx context.Context, arg ResolveErrorGroupParams) (ErrorGroup, error)
	RetryFailedDeliveries(ctx context.Context, attempt int32) (pgconn.CommandTag, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	RevokeAllSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	SearchErrorGroups(ctx context.Context, arg SearchErrorGroupsParams) ([]ErrorGroup, error)
	TouchAPIKey(ctx context.Context, id uuid.UUID) error
	TouchSession(ctx context.Context, id uuid.UUID) error
	UnverifyUserEmail(ctx context.Context, arg UnverifyUserEmailParams) error
	UpdateAnonProfile(ctx context.Context, arg UpdateAnonProfileParams) (AnonProfile, error)
	UpdateAnonProfileStatus(ctx context.Context, arg UpdateAnonProfileStatusParams) (AnonProfile, error)
	UpdateEnvironment(ctx context.Context, arg UpdateEnvironmentParams) (Environment, error)
	UpdateEnvironmentStatus(ctx context.Context, arg UpdateEnvironmentStatusParams) error
	UpdateFeatureFlags(ctx context.Context, arg UpdateFeatureFlagsParams) (Environment, error)
	UpdateNotificationChannel(ctx context.Context, arg UpdateNotificationChannelParams) (NotificationChannel, error)
	UpdatePerfBudget(ctx context.Context, arg UpdatePerfBudgetParams) (PerfBudget, error)
	UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) error
	UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (Subscription, error)
	UpdateSubscriptionStripeIDs(ctx context.Context, arg UpdateSubscriptionStripeIDsParams) (Subscription, error)
	UpdateTenantPlan(ctx context.Context, arg UpdateTenantPlanParams) (Tenant, error)
	UpdateTenantRetention(ctx context.Context, arg UpdateTenantRetentionParams) (Tenant, error)
	UpdateTenantSettings(ctx context.Context, arg UpdateTenantSettingsParams) (Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpsertErrorGroup(ctx context.Context, arg UpsertErrorGroupParams) (ErrorGroup, error)
	VerifyUserEmail(ctx context.Context, arg VerifyUserEmailParams) error
}

var _ Querier = (*Queries)(nil)
