// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: schema_snapshots.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const countSchemasByEnv = `-- name: CountSchemasByEnv :one
SELECT count(*) FROM schema_snapshots
WHERE env_id = $1
`

func (q *Queries) CountSchemasByEnv(ctx context.Context, envID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSchemasByEnv, envID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSchemaSnapshot = `-- name: CreateSchemaSnapshot :one
INSERT INTO schema_snapshots (
    env_id,
    version,
    models,
    model_count,
    field_count,
    diff_ref
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, env_id, captured_at, models, model_count, field_count, diff_ref, version
`

type CreateSchemaSnapshotParams struct {
	EnvID      uuid.UUID       `db:"env_id" json:"env_id"`
	Version    *string         `db:"version" json:"version"`
	Models     json.RawMessage `db:"models" json:"models"`
	ModelCount *int32          `db:"model_count" json:"model_count"`
	FieldCount *int32          `db:"field_count" json:"field_count"`
	DiffRef    *string         `db:"diff_ref" json:"diff_ref"`
}

func (q *Queries) CreateSchemaSnapshot(ctx context.Context, arg CreateSchemaSnapshotParams) (SchemaSnapshot, error) {
	row := q.db.QueryRow(ctx, createSchemaSnapshot,
		arg.EnvID,
		arg.Version,
		arg.Models,
		arg.ModelCount,
		arg.FieldCount,
		arg.DiffRef,
	)
	var i SchemaSnapshot
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.CapturedAt,
		&i.Models,
		&i.ModelCount,
		&i.FieldCount,
		&i.DiffRef,
		&i.Version,
	)
	return i, err
}

const deleteOldSchemaSnapshots = `-- name: DeleteOldSchemaSnapshots :execresult
DELETE FROM schema_snapshots
WHERE id IN (
    SELECT s.id
    FROM schema_snapshots s
    JOIN environments e ON s.env_id = e.id
    WHERE e.tenant_id = $1
    AND s.id NOT IN (
        SELECT s2.id
        FROM schema_snapshots s2
        WHERE s2.env_id = s.env_id
        ORDER BY s2.captured_at DESC
        LIMIT $2
    )
)
`

type DeleteOldSchemaSnapshotsParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	Limit    int32     `db:"limit" json:"limit"`
}

// Keep the N most recent per env, delete the rest for a tenant
// Call from retention worker with the keep count
func (q *Queries) DeleteOldSchemaSnapshots(ctx context.Context, arg DeleteOldSchemaSnapshotsParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteOldSchemaSnapshots, arg.TenantID, arg.Limit)
}

const getLatestSchema = `-- name: GetLatestSchema :one
SELECT id, env_id, captured_at, models, model_count, field_count, diff_ref, version FROM schema_snapshots
WHERE env_id = $1
ORDER BY captured_at DESC
LIMIT 1
`

func (q *Queries) GetLatestSchema(ctx context.Context, envID uuid.UUID) (SchemaSnapshot, error) {
	row := q.db.QueryRow(ctx, getLatestSchema, envID)
	var i SchemaSnapshot
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.CapturedAt,
		&i.Models,
		&i.ModelCount,
		&i.FieldCount,
		&i.DiffRef,
		&i.Version,
	)
	return i, err
}

const getSchemaByID = `-- name: GetSchemaByID :one
SELECT id, env_id, captured_at, models, model_count, field_count, diff_ref, version FROM schema_snapshots
WHERE id = $1 AND env_id = $2
LIMIT 1
`

type GetSchemaByIDParams struct {
	ID    uuid.UUID `db:"id" json:"id"`
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
}

func (q *Queries) GetSchemaByID(ctx context.Context, arg GetSchemaByIDParams) (SchemaSnapshot, error) {
	row := q.db.QueryRow(ctx, getSchemaByID, arg.ID, arg.EnvID)
	var i SchemaSnapshot
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.CapturedAt,
		&i.Models,
		&i.ModelCount,
		&i.FieldCount,
		&i.DiffRef,
		&i.Version,
	)
	return i, err
}

const getSchemaSnapshotByID = `-- name: GetSchemaSnapshotByID :one
SELECT id, env_id, captured_at, models, model_count, field_count, diff_ref, version FROM schema_snapshots
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetSchemaSnapshotByID(ctx context.Context, id uuid.UUID) (SchemaSnapshot, error) {
	row := q.db.QueryRow(ctx, getSchemaSnapshotByID, id)
	var i SchemaSnapshot
	err := row.Scan(
		&i.ID,
		&i.EnvID,
		&i.CapturedAt,
		&i.Models,
		&i.ModelCount,
		&i.FieldCount,
		&i.DiffRef,
		&i.Version,
	)
	return i, err
}

const getTwoSchemasForDiff = `-- name: GetTwoSchemasForDiff :many
SELECT id, env_id, captured_at, models, model_count, field_count, diff_ref, version FROM schema_snapshots
WHERE id = ANY($1::uuid[])
ORDER BY captured_at ASC
`

func (q *Queries) GetTwoSchemasForDiff(ctx context.Context, dollar_1 []uuid.UUID) ([]SchemaSnapshot, error) {
	rows, err := q.db.Query(ctx, getTwoSchemasForDiff, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SchemaSnapshot{}
	for rows.Next() {
		var i SchemaSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.CapturedAt,
			&i.Models,
			&i.ModelCount,
			&i.FieldCount,
			&i.DiffRef,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchemaSnapshots = `-- name: ListSchemaSnapshots :many
SELECT id, env_id, captured_at, version, model_count, field_count, diff_ref
FROM schema_snapshots
WHERE env_id = $1
ORDER BY captured_at DESC
LIMIT $2
`

type ListSchemaSnapshotsParams struct {
	EnvID uuid.UUID `db:"env_id" json:"env_id"`
	Limit int32     `db:"limit" json:"limit"`
}

type ListSchemaSnapshotsRow struct {
	ID         uuid.UUID `db:"id" json:"id"`
	EnvID      uuid.UUID `db:"env_id" json:"env_id"`
	CapturedAt time.Time `db:"captured_at" json:"captured_at"`
	Version    *string   `db:"version" json:"version"`
	ModelCount *int32    `db:"model_count" json:"model_count"`
	FieldCount *int32    `db:"field_count" json:"field_count"`
	DiffRef    *string   `db:"diff_ref" json:"diff_ref"`
}

func (q *Queries) ListSchemaSnapshots(ctx context.Context, arg ListSchemaSnapshotsParams) ([]ListSchemaSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listSchemaSnapshots, arg.EnvID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSchemaSnapshotsRow{}
	for rows.Next() {
		var i ListSchemaSnapshotsRow
		if err := rows.Scan(
			&i.ID,
			&i.EnvID,
			&i.CapturedAt,
			&i.Version,
			&i.ModelCount,
			&i.FieldCount,
			&i.DiffRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
