// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package db

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgconn"
)

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (
    user_id,
    tenant_id,
    refresh_token,
    user_agent,
    ip_address,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, tenant_id, refresh_token, user_agent, ip_address, expires_at, created_at, last_used_at
`

type CreateSessionParams struct {
	UserID       uuid.UUID   `db:"user_id" json:"user_id"`
	TenantID     uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	RefreshToken string      `db:"refresh_token" json:"refresh_token"`
	UserAgent    *string     `db:"user_agent" json:"user_agent"`
	IpAddress    *netip.Addr `db:"ip_address" json:"ip_address"`
	ExpiresAt    time.Time   `db:"expires_at" json:"expires_at"`
}

// ════════════════════════════════════════════
//
//	Sessions
//
// ════════════════════════════════════════════
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.TenantID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execresult
DELETE FROM sessions
WHERE expires_at < now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteExpiredSessions)
}

const getSession = `-- name: GetSession :one
SELECT
    s.id, s.user_id, s.tenant_id, s.refresh_token, s.user_agent, s.ip_address, s.expires_at, s.created_at, s.last_used_at,
    u.is_active AS user_is_active
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.id = $1
LIMIT 1
`

type GetSessionRow struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	UserID       uuid.UUID   `db:"user_id" json:"user_id"`
	TenantID     uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	RefreshToken string      `db:"refresh_token" json:"refresh_token"`
	UserAgent    *string     `db:"user_agent" json:"user_agent"`
	IpAddress    *netip.Addr `db:"ip_address" json:"ip_address"`
	ExpiresAt    time.Time   `db:"expires_at" json:"expires_at"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
	LastUsedAt   time.Time   `db:"last_used_at" json:"last_used_at"`
	UserIsActive bool        `db:"user_is_active" json:"user_is_active"`
}

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.UserIsActive,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT
    s.id, s.user_id, s.tenant_id, s.refresh_token, s.user_agent, s.ip_address, s.expires_at, s.created_at, s.last_used_at,
    u.is_active AS user_is_active
FROM sessions s
JOIN users u ON s.user_id = u.id
WHERE s.refresh_token = $1
  AND s.expires_at > now()
LIMIT 1
`

type GetSessionByTokenRow struct {
	ID           uuid.UUID   `db:"id" json:"id"`
	UserID       uuid.UUID   `db:"user_id" json:"user_id"`
	TenantID     uuid.UUID   `db:"tenant_id" json:"tenant_id"`
	RefreshToken string      `db:"refresh_token" json:"refresh_token"`
	UserAgent    *string     `db:"user_agent" json:"user_agent"`
	IpAddress    *netip.Addr `db:"ip_address" json:"ip_address"`
	ExpiresAt    time.Time   `db:"expires_at" json:"expires_at"`
	CreatedAt    time.Time   `db:"created_at" json:"created_at"`
	LastUsedAt   time.Time   `db:"last_used_at" json:"last_used_at"`
	UserIsActive bool        `db:"user_is_active" json:"user_is_active"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, refreshToken string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, refreshToken)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.UserIsActive,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id, user_id, tenant_id, refresh_token, user_agent, ip_address, expires_at, created_at, last_used_at
FROM sessions
WHERE user_id = $1
  AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) ListSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TenantID,
			&i.RefreshToken,
			&i.UserAgent,
			&i.IpAddress,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessions = `-- name: RevokeAllSessions :exec
DELETE FROM sessions
WHERE user_id = $1
`

func (q *Queries) RevokeAllSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
DELETE FROM sessions
WHERE id = $1 AND user_id = $2
`

type RevokeSessionParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.UserID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateSessionToken = `-- name: UpdateSessionToken :exec
UPDATE sessions
SET refresh_token = $2,
    expires_at = $3,
    last_used_at = now()
WHERE id = $1
`

type UpdateSessionTokenParams struct {
	ID           uuid.UUID `db:"id" json:"id"`
	RefreshToken string    `db:"refresh_token" json:"refresh_token"`
	ExpiresAt    time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) UpdateSessionToken(ctx context.Context, arg UpdateSessionTokenParams) error {
	_, err := q.db.Exec(ctx, updateSessionToken, arg.ID, arg.RefreshToken, arg.ExpiresAt)
	return err
}
