package service

import (
	"context"
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"time"

	db "Intelligent_Dev_ToolKit_Odoo/db/sqlc"
	"Intelligent_Dev_ToolKit_Odoo/internal/api"
	"Intelligent_Dev_ToolKit_Odoo/internal/dto"
	"Intelligent_Dev_ToolKit_Odoo/utils"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

// AgentRegisterService handles agent self-registration using one-time tokens.
type AgentRegisterService struct {
	store db.Store
}

func NewAgentRegisterService(store db.Store) *AgentRegisterService {
	return &AgentRegisterService{store: store}
}

// SelfRegister validates a one-time registration token and returns agent credentials.
// It generates an agent_id and API key, then clears the token so it cannot be reused.
func (s *AgentRegisterService) SelfRegister(ctx context.Context, req *dto.AgentSelfRegisterRequest) (*dto.AgentSelfRegisterResponse, error) {
	// 1. Look up environment by registration token.
	token := req.RegistrationToken
	env, err := s.store.GetEnvironmentByRegistrationToken(ctx, &token)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, api.ErrUnauthorized("invalid or expired registration token")
		}
		return nil, api.ErrInternal(err)
	}

	// 2. Generate agent ID.
	agentID := uuid.New().String()

	// 3. Generate API key.
	rawBytes := make([]byte, 32)
	if _, err := rand.Read(rawBytes); err != nil {
		return nil, api.ErrInternal(fmt.Errorf("generate key: %w", err))
	}
	rawKey := "odt_" + base64.RawURLEncoding.EncodeToString(rawBytes)

	prefix := rawKey
	if len(prefix) > 12 {
		prefix = prefix[:12]
	}
	keyHash := utils.HashAPIKey(rawKey)

	expiresAt := time.Now().UTC().Add(90 * 24 * time.Hour)
	envID := env.ID

	if _, err := s.store.CreateAPIKey(ctx, db.CreateAPIKeyParams{
		TenantID:      env.TenantID,
		EnvironmentID: &envID,
		CreatedBy:     nil, // system-generated, no user
		KeyHash:       keyHash,
		KeyPrefix:     prefix,
		Name:          "agent-" + agentID[:8],
		Description:   "Auto-generated by agent self-registration",
		Scopes:        []string{"agent:write"},
		ExpiresAt:     &expiresAt,
	}); err != nil {
		return nil, api.ErrInternal(fmt.Errorf("create api key: %w", err))
	}

	// 4. Clear token and set agent_id on the environment.
	if err := s.store.ClearRegistrationToken(ctx, db.ClearRegistrationTokenParams{
		ID:      env.ID,
		AgentID: &agentID,
	}); err != nil {
		return nil, api.ErrInternal(fmt.Errorf("clear token: %w", err))
	}

	return &dto.AgentSelfRegisterResponse{
		AgentID:       agentID,
		APIKey:        rawKey,
		EnvironmentID: env.ID.String(),
		TenantID:      env.TenantID.String(),
	}, nil
}
